### ISSUE TITLE
Remote virtualization sample should load data source with more records

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular-samples#1017]
### Description  
Change remote virtualization sample (http://localhost:4200/grid/grid-sample-4) to load data source with couple of hundreds of records.

**Note:** Requested by @SlavUI

**Comment by ChronosSF** [comment]
The issue is no longer valid. We changed the cache already and the sample looks good as it is. Other data sources will make the data inside not as varied.
