### ISSUE TITLE
Expanding child grids in Hierarchical Grid Column Pinning is broken

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-angular-samples#1018]
### Steps to reproduce  

1. Open the Hierarchical Grid Column Pinning sample
2. Expand a child grid

### Result  
```typescript 
ERROR TypeError: Cannot read property 'field' of undefined
```

### Expected result  
No errors should be thrown

**Comment by mpavlinov** [comment]
@rkaraivanov I cannot reproduce it. It was probably fixed in RC1.

**Comment by rkaraivanov** [comment]
Yes, it is working now.
