### ISSUE TITLE
Transaction dialog is not centered in the grid batch editing sample in IE

### ISSUE THREAD

**Issue by PlamenaMiteva** [IgniteUI/igniteui-angular-samples#1032]
### Description  
Transaction dialog is not centered in the grid batch editing template in IE

### Steps to reproduce  

1. Open grid or tree grid batch editing sample in IE
2. Edit a row and press commit button

### Result  
Transaction dialog is partially visible

### Expected result  
Transaction dialog should be centered and visible.

### Attachments  
![screenshot 5](https://user-images.githubusercontent.com/10612538/53884437-3db84e80-4024-11e9-9b47-42aed92b875b.png)

**Comment by Lipata** [comment]
https://github.com/IgniteUI/igniteui-angular/issues/4220
