### ISSUE TITLE
Link to GitHub is incorrect in all grid, tree grid and hierarchical grid samples

### ISSUE THREAD

**Issue by PlamenaMiteva** [IgniteUI/igniteui-angular-samples#1034]
### Description  
Incorrect link to GitHub in grid, tree grid and hierarchical grid samples

**Comment by PlamenaMiteva** [comment]
Created the issue in the igniteui-docfx repo
https://github.com/IgniteUI/igniteui-docfx/issues/1089

**Comment by mpavlinov** [comment]
@PlamenaMiteva There is a "Transfer Issue" functionality. No need to close and create a new issue.
