### ISSUE TITLE
Samples in StackBlitz do not work in EDGE

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular-samples#1059]
### Description  
Any sample opened from the "View on StackBlitz" button in Edge does not work

### Steps to reproduce  

Open any sample from "View on StackBlitz" button in Edge

### Result  
The sample does not work

### Expected result  
The sample should work

P.S. This could be related with the sass framework, which also makes problems in IE11. The samples opened from the topics use scss for default styling(in EDGE ) in StackBlitz, but if you open a sample with css styling it works fine.

Open these in EDGE
[CSS IgxGrid sample](https://stackblitz.com/edit/angular-kg3vq3)

[SCSS IgxGrid sample](https://stackblitz.com/edit/angular-7xva2w)

**Comment by tiliev** [comment]
This is not related to our samples or the IE 11 `Out of stack space` [issue](https://github.com/stackblitz/core/issues/476). Their own starter does not work with Sass on Edge anymore - https://stackblitz.com/edit/sb-starter-scss. This seems to be a third-party issue and should be reported to the StackBlitz team. Until it's fixed we could load the CSS samples in the Edge, too. [Here](https://github.com/IgniteUI/igniteui-docfx-template/blob/master/template/styles/stackblitz-handler.js#L93) is the function which loads the samples depending on the browser.

**Comment by mpavlinov** [comment]
@tiliev Thank you!

**Comment by zdrawku** [comment]
much appreciate your help 😃

**Comment by zdrawku** [comment]
I've logged issue in stackblitz https://github.com/stackblitz/core/issues/894

@HristoP96 for the time being lets use CSS in the Edge samples also.

**Comment by HristoP96** [comment]
Another issue is [logged in StackBlitz](https://github.com/stackblitz/core/issues/927), regarding its behavior in Microsoft Edge. It has an impact on the classes applied to the body element in index.html, which in our case are the "dark-green" and "igx-typography" classes.  
This does is not break the samples like the SCSS usage, so I will make a PR for using CSS in Edge

**Comment by HristoP96** [comment]
This issue is fixed with this [PR](https://github.com/IgniteUI/igniteui-docfx-template/pull/95/files)
