### ISSUE TITLE
Disabled Stackblitz buttons in a coupled of samples from PR #1055 

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-samples#1063]
1. Check out the branch from PR #1055 from the docfx repository:
https://github.com/IgniteUI/igniteui-docfx/pull/1055/files
2. Build the documentation and run it with npm run start -- --lang=jp
3. Open the following samples:
http://localhost:3000/components/categorychart_high_volume_data.html
http://localhost:3000/components/categorychart_real_time_data.html
http://localhost:3000/components/datachart_axis_scales.html
http://localhost:3000/components/datachart_axis_types.html
http://localhost:3000/components/datachart_chart_performance.html
http://localhost:3000/components/datachart_chart_synchronization.html
http://localhost:3000/components/datachart_data_triangulation.html
http://localhost:3000/components/datachart_series_animations.html
http://localhost:3000/components/datachart_series_errorbars.html
http://localhost:3000/components/datachart_series_requirements.html
http://localhost:3000/components/datachart_series_types_scatter_hd.html
http://localhost:3000/components/datachart_series_types_stacked.html
http://localhost:3000/components/datachart_series_value_overlay.html
http://localhost:3000/components/excel_library_using_cells.html
http://localhost:3000/components/excel_library_using_tables.html
http://localhost:3000/components/excel_library_using_workbooks.html
http://localhost:3000/components/excel_library_using_worksheets.html
http://localhost:3000/components/excel_library_working_with_charts.html
http://localhost:3000/components/excel_library_working_with_grids.html
http://localhost:3000/components/excel_library_working_with_sparklines.html
http://localhost:3000/components/financialchart_custom_tooltips.html

There is at least one sample in these pages which has its Stackblitz button disabled.

**Comment by zdrawku** [comment]
@HUSSAR-mtrela we are going to make this change, @HristoP96 is going to PR the change in the internal repository cplat-docfx, and this change will cover all lazy loading configurations and iframe id's. The issue above is cause by the incorrect id's

**Comment by zdrawku** [comment]
resolved
