### ISSUE TITLE
Disabled Stackblitz buttons in a coupled of samples from PR #1056

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-samples#1064]
1. Check out the branch from PR #1056 from the docfx repository.
2. Build the documentation and run it with npm run start -- --lang=kr
3. Open the following pages:
http://localhost:3000/components/datachart_axis.html
http://localhost:3000/components/datachart_chart_performance.html
http://localhost:3000/components/datachart_chart_synchronization.html
http://localhost:3000/components/datachart_series_animations.html
http://localhost:3000/components/datachart_series_errorbars.html
http://localhost:3000/components/datachart_series_requirements.html
http://localhost:3000/components/datachart_series_types_stacked.html
http://localhost:3000/components/datachart_series_value_overlay.html
http://localhost:3000/components/excel_library_using_cells.html
http://localhost:3000/components/excel_library_using_workbooks.html
http://localhost:3000/components/excel_library_using_worksheets.html
http://localhost:3000/components/excel_library_working_with_charts.html
http://localhost:3000/components/excel_library_working_with_grids.html
http://localhost:3000/components/excel_library_working_with_sparklines.html
http://localhost:3000/components/excel_library_using_tables.html
http://localhost:3000/components/financialchart_binding_to_multiple_data.html

The pages contain at least one sample which has its Stackblitz button disabled.

**Comment by zdrawku** [comment]
Same as https://github.com/IgniteUI/igniteui-angular-samples/issues/1063#issuecomment-484091663
