### ISSUE TITLE
A couple of samples in JP staging don't start

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-samples#1065]
### Description  
A couple of sample from the JP docfx documentation on staging don't start.

### Steps to reproduce  

1. Open https://jp.staging.infragistics.local/products/ignite-ui-angular/angular/components/financialchart_custom_tooltips.html

https://jp.staging.infragistics.local/products/ignite-ui-angular/angular/components/categorychart.html
https://jp.staging.infragistics.local/products/ignite-ui-angular/angular/components/doughnutchart.html - Legend Demo

2. Examine the samples in the pages.

### Result  
The samples don't show up.

### Expected result  
The samples should show up.

**Comment by zdrawku** [comment]
Same as https://github.com/IgniteUI/igniteui-angular-samples/issues/1063#issuecomment-484091663
