### ISSUE TITLE
Disabled Stackblitz buttons on JP staging

### ISSUE THREAD

**Issue by valadzhov** [IgniteUI/igniteui-angular-samples#1066]
### Description  
The Stackblitz buttons are disabled for the samples in some pages.

### Steps to reproduce  

1. Open the following pages:
https://jp.staging.infragistics.local/products/ignite-ui-angular/angular/components/categorychart_tooltip_templates.html
https://jp.staging.infragistics.local/products/ignite-ui-angular/angular/components/chip.html
https://jp.staging.infragistics.local/products/ignite-ui-angular/angular/components/card.html
https://jp.staging.infragistics.local/products/ignite-ui-angular/angular/components/categorychart_real_time_data.html
2. Examine the samples.

### Result  
The Stackblitz button of the samples is disabled.

### Expected result  
The button should be active.

**Comment by zdrawku** [comment]
Same as https://github.com/IgniteUI/igniteui-angular-samples/issues/1063#issuecomment-484091663
