### ISSUE TITLE
Update awesome grid sample

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#107]
### Description  
We would like for the scroll of the grid to be removed and for the paging to be add again.

A new sample of the Grid will be created which will include virtualization on a later stage.

- [ ] Add paging

**Comment by kdinev** [comment]
@zdrawku Update: After the grid is sorted by the first column (who's currently leading the race), the column header does not indicate that the column is sorted. In other words, the arrow is missing.
