### ISSUE TITLE
Angular samples styling issues.

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular-samples#109]
### Description  
Several angular samples styling issues.

### Steps to reproduce  
1. Go to https://staging.infragistics.local/products/ignite-ui-angular/angular/components/buttongroup.html
2. Click on the "format align left" button.
3. Click on "London" button.

4. Go to https://staging.infragistics.local/products/ignite-ui-angular/angular/components/button.html
5. Inspect the "Disabled" button.

6. Go to the bottom of the page to last demo.
7. Inspect the two icon buttons.

### Result  
**2. and 3:**
The background of the selected button is not visible
![buttongroup](https://user-images.githubusercontent.com/11095014/36668854-4df4e08c-1afb-11e8-9abe-b239d7c020ea.png)
**5.** The background is not set. The font is not set.
![button](https://user-images.githubusercontent.com/11095014/36670839-3514a000-1b02-11e8-8b3b-8ec338e1bca1.png)

**7.** The icon buttons are positioned vertically:
![button2](https://user-images.githubusercontent.com/11095014/36671263-a0d4f3de-1b03-11e8-9dc5-5fe35b94a60f.png)

### Expected result  
**2. and 3.**
The background of the selected button should be visible.
**Note:** when Vertical selection is used only the bottom border of the selected is visible, which is different from  horizontal selection when both left and right borders are visible.
![buttongroupexpected](https://user-images.githubusercontent.com/11095014/36671057-03cfa1e2-1b03-11e8-999b-8e3c266672ff.png)
**5.**The background should be set. The font should be set.
![buttonexpected](https://user-images.githubusercontent.com/11095014/36670981-bcc2add0-1b02-11e8-82b1-dfc1b04b7cd8.png)
**7.** The icon buttons should be positioned horizontally:
![button2expected](https://user-images.githubusercontent.com/11095014/36671330-e36a8a1a-1b03-11e8-9e60-1c81aad6508d.png)

**Comment by simeonoff** [comment]
@npaunov 

1. You have set *background-color* to the buttons in the button-group to white using JavaScript, which overrides the CSS class properties.
2. This is how the *disabled* state of a flat button should look like.
3. Log a feature request regarding the display type for buttons of type icon. I agree it should be _inline-flex_, instead of flex;
