### ISSUE TITLE
HGrid Editing and Pinning samples throw an error

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular-samples#1099]
### Description  
Trying to open the HierarchicalGrid Editing and Pinning samples shows errors in the console and the grids fail to initialize.

### Steps to reproduce  

1. Open https://staging.infragistics.local/products/ignite-ui-angular/angular/components/hierarchicalgrid/column_pinning.html or https://staging.infragistics.local/products/ignite-ui-angular/angular/components/hierarchicalgrid/editing.html
2. Open the console

### Result  
The grids do not get initialized, there are errors in the console

### Expected result  
The grids to render without errors

### Attachments  
![Sketch](https://user-images.githubusercontent.com/18643062/55862477-3800dc00-5b81-11e9-8b27-739697089da5.png)

**Comment by mpavlinov** [comment]
@PavlovVasil I can reproduce it for this sample as well: http://localhost:4200/samples/hierarchical-grid/hierarchical-grid-custom-hiding

**Comment by PavlovVasil** [comment]
@mpavlinov Because of [this issue](https://github.com/IgniteUI/igniteui-angular/issues/4491) I have added a separate width of '200px' to each column, which i change to '20%' in ngAfterViewInit. Otherwise there is some empty space after the last column, which looks a little bit odd.
