### ISSUE TITLE
Demos User Story creation and refactoring

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular-samples#11]
Lest create user Stories for the Ignite UI for Angular Demos and implement them.

The design team will create the Stories and present them in the end of Sprint 2

**Comment by SlavUI** [comment]
Hi All as agreed on the meeting today lets have an user story for each Demo in order to improve UX.

**Comment by simeonoff** [comment]
This has been resolved with https://github.com/IgniteUI/igniteui-docfx/pull/41.
