### ISSUE TITLE
Legend Demo contains blank iframe

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular-samples#1111]
### Description  
The  demo for doughnut chart does not render anything

### Steps to reproduce  
Open this link in production:
[https://www.infragistics.com/products/ignite-ui-angular/angular/components/doughnutchart.html#legend](https://www.infragistics.com/products/ignite-ui-angular/angular/components/doughnutchart.html#legend)
### Result  
There is no sample in the iframe and the stackblitz button generates [doughnut explosion sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/doughnutchart.html#slice-explosion)

### Expected result  
A demo for doughnut chart legend should be rendered in the iframe and the Stackblitz button should generate this demo in stackblitz

### Attachments  
Production:
![prod](https://user-images.githubusercontent.com/25771040/56034617-74266f00-5d30-11e9-9e18-b7c63c77579a.PNG)

![prodsrc](https://user-images.githubusercontent.com/25771040/56034629-7be61380-5d30-11e9-8a3c-24b2736e7905.PNG)

**Comment by hanastasov** [comment]
Not reproducible anymore:
![image](https://user-images.githubusercontent.com/14248932/83613494-85fa4f80-a58c-11ea-9202-42e620d168de.png)
