### ISSUE TITLE
Error is thrown when try to edit cell

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular-samples#1125]
### Steps to reproduce  

1. Open [Grid Editing Sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing.html)
2. Double click over cell from the column **Available At**
3. Observe the console

### Result  
What is the actual result after following the steps to reproduce?
![image](https://user-images.githubusercontent.com/34240583/56268211-6fc7d080-60f9-11e9-85f5-1c30b863c6e6.png)

### Expected result  
What is the expected result after following the steps to reproduce?
No errors should be thrown in the console.

**Comment by HristoP96** [comment]
This issue is reproducible also in [Grid Batch Editing sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/batch_editing.html)
