### ISSUE TITLE
Enhance context menu demo and move it to new topic

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#1146]
### Description  
The [context menu demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/sorting.html#demo) should be removed from the sorting sample and we need to create much richer demonstration in a new topic

![image](https://user-images.githubusercontent.com/11193764/57379246-3b52ac00-71af-11e9-846b-149cf4904a9a.png)

**Comment by HristoP96** [comment]
This is done
- [https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection.html#grid-context-menu](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection.html#grid-context-menu)
