### ISSUE TITLE
Exclusive button group behavior is not correct

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#1152]
### Description  
The exclusive selection should always have one selected item, the current implementation allows deselecting of the currently selected item

https://www.infragistics.com/products/ignite-ui-angular/angular/components/buttongroup.html#button-group-demo

**Comment by StefanIvanov** [comment]
The [Material spec](https://material.io/components/buttons/#) makes no specific point in favor of this bug, furthermore it shows examples of button groups that have no selection. The current behavior is by design and should not be considered a bug.
