### ISSUE TITLE
"Fatal process OOM in insufficient memory to create an Isolate" when building the repo

### ISSUE THREAD

**Issue by dafo** [IgniteUI/igniteui-angular-samples#1166]
### Description  
Describe the issue.

### Steps to reproduce  

1. Clone the repo
2. Run `npm install`
3. Run `npm run build` or `npm run start:live-editing`

### Result  
Fatal process OOM in insufficient memory to create an Isolate
#

npm ERR! code ELIFECYCLE
npm ERR! errno 3221225477
npm ERR! igniteui-angular-samples@1.0.0 build: `gulp generate-live-editing && node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng build --prod --aot=true --vendor-source-map=false --progress=true`
npm ERR! Exit status 3221225477

### Expected result  
no exception.
project builds

Note:
![screenshot2](https://user-images.githubusercontent.com/2778393/58015678-856b5400-7b04-11e9-8391-a8ba99fca333.png)

### Attachments  

![screenshot](https://user-images.githubusercontent.com/2778393/58015561-41784f00-7b04-11e9-97fe-c05d00aa8c91.png)

**Comment by mbektas7** [comment]
is it solved?

**Comment by RupengLiu** [comment]
same issue here

**Comment by velz2020** [comment]
Same Issue in Windows.

**Comment by HristoP96** [comment]
This is no longer reproducible. The fix is in this [PR](https://github.com/IgniteUI/igniteui-angular-samples/pull/1697/files).
