### ISSUE TITLE
Selection based summaries sample

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular-samples#1170]
Add "Selection based summaries" as a new section with a sample scenario to the existing [grid selection topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/selection.html#grid-row-selection) after the "Row Selection" section and before "Setup". The height of the row that is added at the bottom matches the summary row display density for the configured density setting and keeps a padding on the right that also matches the one of a summary cell.

![Selection Aggregates 1](https://user-images.githubusercontent.com/1702064/58487046-a1f43580-816f-11e9-9b8b-a5f199bffc5d.png)
![Selection Aggregates 2](https://user-images.githubusercontent.com/1702064/58487052-a3bdf900-816f-11e9-962a-b0d376ee1a62.png)

**Comment by mpavlinov** [comment]
@StefanIvanov Is the use of term "aggregates" on purpose? I think we can use the term "summaries" instead.

**Comment by StefanIvanov** [comment]
You are right the two are used interchangably so let's use summaries instead.
