### ISSUE TITLE
Update samples browser to Angular 8 

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular-samples#1184]
### Description  
Update to the latest Angular v8.

**Comment by eestein** [comment]
I've just upgraded to angular v8 and some CSS errors are popping up, is there a version of ignite-ui supporting angular 8?

**Comment by IvayloG** [comment]
There is a beta version available https://github.com/IgniteUI/igniteui-angular/releases/tag/8.0.0-beta.0
and there will be an official version very soon.

**Comment by damyanpetev** [comment]
@eestein I think I've seen a similar error. It was to do with a change in the sass compiler used by the Angular 8 cli builders - new features/capabilities we make use of already.
However it's either multiple versions of it in the dep tree or npm just messes up the update completely. What helped was deleting `node_modules` and the `package-lock.json` and regenerating it with a new install.

PS: Actually, make that [8.0.0-beta.1](https://github.com/IgniteUI/igniteui-angular/releases/tag/8.0.0-beta.1).
(Package deps needed updating)

**Comment by eestein** [comment]
@IvayloG @damyanpetev thanks for your answers... I did both, installed the beta version `"igniteui-angular": "^8.0.0-beta.1",` and also removed `node_modules` and `package-lock.json` for a fresh install, and after importing the theme:

```
@import "~igniteui-angular/lib/core/styles/themes/index";

@include igx-core;
@include igx-theme($default-palette);
```

 I get the same error. Any other ideas? Thanks.

**Comment by damyanpetev** [comment]
@eestein You're right, that didn't quite work.
It must be some other dependency on [`node-sass`](https://www.npmjs.com/package/node-sass) and the fresh install made it (or the loader) resurface as top-level and get picked up by the [sass-loader](https://github.com/webpack-contrib/sass-loader) as it defaults to that over the dart version.

However, in a fresh project nothing in the Angular build packages dependends on node-sass after updating to 8 and thus the re-install does nothing.

We'll be updating our themes to compile correctly with Dart Sass, see https://github.com/IgniteUI/igniteui-angular/issues/5077. In the meantime a workaround would be to install `node-sass` manually as dev dep: https://github.com/IgniteUI/igniteui-angular/issues/5077#issuecomment-502074060

**Comment by eestein** [comment]
Thanks @damyanpetev adding the dev dependency for `node-sass` worked. This will allow to continue development while I wait for the final version 👍
