### ISSUE TITLE
Update column-hiding/grid-moving samples 

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular-samples#1205]
### Description  
The grid column-hiding/grid-moving samples throw errors. 

### Steps to reproduce  

1. Run the samples browser
2. First open a random sample.
3. Then navigate to http://localhost:4200/samples/grid/grid-column-hiding-sample
4*. The same applies for http://localhost:4200/samples/grid/grid-moving-sample

### Result  
Inspect the console:
VM21346 GridColumnHidingSampleComponent.ngfactory.js:11 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'columns: '. Current value: 'columns: [object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object],[object Object]'.

### Expected result  
Run without an error as on production.

https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column_hiding.html

### Attachments  
![image](https://user-images.githubusercontent.com/4296944/59770764-3d7d4f80-92b1-11e9-83db-d98b1eca5a9a.png)

**Comment by ddincheva** [comment]
The problem with column hiding sample is addressed [here](https://github.com/IgniteUI/igniteui-angular/issues/7681)
