### ISSUE TITLE
Stackblitz samples won't load in IE11 with Angular 8

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular-samples#1226]
### Description  
Loading samples with Angular 8 dependencies **(not dev)** doesn't load under IE11.
This is probably due to the conditional polyfills we rely on (since angluar/cli@7.3) but the dev deps in SB are not up-to-date:
```json
"devDependencies": {
    "@angular-devkit/build-angular": "~0.10.0",
    "@angular/cli": "~7.0.2",
    "@angular/compiler-cli": "~7.0.0",
    ...
```
This is quite likely what's causing other similar issues (https://github.com/stackblitz/core/issues/1004) as we only have API for 'dependencies'.

@HristoP96 You might be able to work around that by adding the missing poly-s just for IE generation.

### Steps to reproduce  

1. Open the main Data Grid page
2. Click the View on Stackblitz button
3. Observe the console

### Result  
Due to some missing poly the sample fails to load and an error is thrown:
Error: Object doesn't support property or method 'fromCodePoint'

### Expected result  
The sample should load

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/3198469/60282410-8ebfbb80-990f-11e9-8cd5-4c8fa133bdc6.png)

**Comment by gedinakova** [comment]
@HristoP96 Stackblitz does not load on Edge as well.
![image](https://user-images.githubusercontent.com/16817847/60323294-590be880-998a-11e9-944a-ce012e21fb3f.png)

**Comment by damyanpetev** [comment]
@gedinakova Is that a specific sample? Because we can't repro the error.
Loads fine for me on Edge 44.17763.1.0/EdgeHTML 18.17763

**Comment by gedinakova** [comment]
@damyanpetev Nope, happens on all samples. 
Microsoft Edge 42.17134.1.0/ Microsoft EdgeHTML 17.17134 though, I guess I need an update.

**Comment by zdrawku** [comment]
Hristo Popov is currently working on that
