### ISSUE TITLE
IgxButtonModule is missing from the Customize Snackbar stackblitz demo

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular-samples#1243]
### Description  
IgxButtonModule is missing from the Customize Snackbar stackblitz demo.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/snackbar.html#customize-snackbar
2. Go to Demo and open it in stackblitz.

### Result  
The "Load File" button in stackblitz is not styled as igxButton.

### Expected result  
The "Load File" button in stackblitz should be styled as igxButton.

**Comment by astaev** [comment]
![LoadFileBtn](https://user-images.githubusercontent.com/44602698/62465774-5cb83980-b798-11e9-8977-6a68792ca0da.PNG)
LoadFile button looks fine.
