### ISSUE TITLE
Introduce a color picker for changing the primary and secondary colors in a sample

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular-samples#131]
### Description  
Introduce a color picker for changing the primary and secondary colors in a sample. I want to see the theming customization live in a sample, where I can pick two new colors and the sample responds.

**Comment by zdrawku** [comment]
@HristoP96 use this [issue](https://github.com/IgniteUI/igniteui-angular/issues/1384#issuecomment-391680477) as a reference and this [sample](https://stackblitz.com/edit/ignite-ui-angular-theming?file=app%2Fapp.component.scss) as a starting point.

The point of this requirement is to demonstrate the global theme capabilities of our theme library. [This topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/global-theme.html) will help you to gain better understanding on how to create a custom global theme that will use primary and secondary colors. Have a look at the material ui colors library, you can use the [Flat UI palette colors](https://www.materialui.co/flatuicolors).

@hanastasov is going to assist you with everything that is unfamiliar for you.

**Comment by StefanIvanov** [comment]
Add the dark theme to the UI once completed [#2732](https://github.com/IgniteUI/igniteui-angular/issues/2732)

**Comment by StefanIvanov** [comment]
![artboard](https://user-images.githubusercontent.com/1702064/49159037-3bab6900-f32c-11e8-9549-1ac7c44bf201.png)
