### ISSUE TITLE
Slider's width from Live Updating Demo extends infinitely on iPad

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular-samples#1315]
### Description  
Slider's width from Live Updating Demo extends infinitely on iPad.

### Steps to reproduce  

1. Open the following sample on IPad:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/live_data.html
2. Observe closely the Records count slider at the top of the Live Updating sample.

### Result  
Slider's width extends infinitely and moves other DOM elements out of view.

### Expected result  
Slider should not extend.

### Attachments  
![ipad](https://user-images.githubusercontent.com/10397980/61532000-345adc00-aa31-11e9-9be7-c94ebee5b1a2.gif)

**Comment by zdrawku** [comment]
After further investigation, it looks like the issue is caused by "display: flex;" usage in the app.

**Comment by Aleksandyr** [comment]
The issue is not reproducible.
It has been tested on **iPhone 11 pro max**, **Ipad Air 2**, and **MacBook 15 pro**.
