### ISSUE TITLE
Stackblitz buttons are disabled in grids' Sorting topics.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular-samples#1332]
### Steps to reproduce  

1. Navigate to Data Grid > Sorting topic
2. Note the Stackblitz buttons for all samples

### Result  
The buttons are disabled.
Note: Valid for all grids.

### Expected result  
The buttons should be enabled.

**Comment by HristoP96** [comment]
@gedinakova Everything is fine now. The new changes are now available on staging:
[https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/sorting.html#styling](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/sorting.html#styling)
