### ISSUE TITLE
Grid Cell Editing demo add dialog is missing paddings

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular-samples#1358]
### Description  
Grid Cell Editing demo add dialog is missing paddings

### Steps to reproduce  

1. Open [Grid Cell Editing](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing.html) demo.
2. Click `Add new product` button

### Result  
The dialog is missing paddings
![image](https://user-images.githubusercontent.com/2621802/62134150-a6140f00-b2e8-11e9-888f-495cfaaa563f.png)

### Expected result  
Provide some paddings between dialog and inputs.

**Comment by radomirchev** [comment]
No longer reproducible
