### ISSUE TITLE
Add row numbering demos for all the grids

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular-samples#1363]
### Description  
Create demos for all the grids with row numbering as a row selector column for the grid.

Similar to [that](https://www.igniteui.com/help/iggrid-configuring-row-selectors#checkboxes-preview) look, just we need to clarify if we want to have both row number and checbox selector, or it is better and clear to template it only with row number. @StefanIvanov what do you think?

**Comment by StefanIvanov** [comment]
We want to have both number and checkbox :)
