### ISSUE TITLE
Remove Dv samples from igniteui-angular-samples

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular-samples#1404]
The Dv samples should be extracted to a new repo and removed from this one

- [x] Guages

- [x] Maps

- [x] Sparkline

- [x] Excel engine

- [x] Spreadsheet

- [x] Zoomslider

- [x] Charts

**Comment by zdrawku** [comment]
We are currently working on the deployment process of angular-samples-dv and the new branching strategy adoption
