### ISSUE TITLE
Slider thumb is not centered in all samples

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular-samples#1483]
### Description  
Slider thumb is not centered in all samples

### Steps to reproduce  

1. Open https://www.infragistics.com/angularsite/components/grid/live_data.html or
https://www.infragistics.com/products/ignite-ui-angular/angular/components/slider.html
2. Look at the slider

Note: The issue is not reproducible in the dark theme

### Result  
Slider thumb is not centered

### Expected result  
slider thump should be centered

### Attachments  

![image](https://user-images.githubusercontent.com/11463104/65310064-1d9e4600-db96-11e9-8575-1c498c8db8ac.png)
![image](https://user-images.githubusercontent.com/7037740/67836941-93cb8c00-faf6-11e9-927d-6e5172a91191.png)

**Comment by zdrawku** [comment]
This is reproducible with the following prerequisite:
- Display scale and layout 125% or above
- Chrome browser
- Laptop with a touch display
- The laptop should not be using docking station

**Comment by Aleksandyr** [comment]
@zdrawku I've reproduced the issue without the above prerequisites.

**Comment by Aleksandyr** [comment]
The issue is not reproducible anymore.
