### ISSUE TITLE
Chart integration sample with igxGrid

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#1485]
### Description  
Create a demonstration of the chart while using the igxGrid, with context menu.

Milestones for creation of decent grid with context menu:

- [x] create context menu component

- [x] add relevant data the grid 

- [ ] add export behavior(to be able also to export the charts)

**create generic chart service, that will render  the following charts based on a grid selection**
       
- [x] Doughnutchart

- [x] Datachart Column Series 

- [x] Datachart Area series 

- [ ] Datachart Waterfall series 

- [x] Datachart Scatter bubble series 

- [x] Datachart Scatter point series

- [x] Piechart

**Comment by zdrawku** [comment]
Mimic the look and feel of the image below, let's have only two tabs for now - Charts and Sparklines. 

![image](https://user-images.githubusercontent.com/11193764/66308497-f70b3980-e90f-11e9-86fe-a245b250d3c7.png)

**Comment by HristoP96** [comment]
Provide the following fixes:

![image](https://user-images.githubusercontent.com/25771040/68198476-cbd64180-ffc4-11e9-9a78-a468f25c02fc.png)

**Comment by zdrawku** [comment]
@radomirchev we've covered the majority of work related to this requirement, for any upcoming type of work, a new issue would be created.
