### ISSUE TITLE
"Live All Prices" button text is cut off in the Live Updating Demo

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular-samples#1492]
### Description  
Describe the issue.
![image](https://user-images.githubusercontent.com/6794133/65664324-c559bf00-e041-11e9-86b6-a37a0e56ddc3.png)

### Steps to reproduce  

1. Open "Live Updating Demo"
2. Observe the "Live All Prices" button text

### Result  
Text is cut off

### Expected result  
Text should not be cut off

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by hanastasov** [comment]
Ellipses is added now. See https://github.com/IgniteUI/igniteui-angular-samples/issues/1760
