### ISSUE TITLE
Excel Style Filtering Sample 2 throws error when expanding a child row

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular-samples#1527]
### Description  
Multiple InvalidPipeArgument errors are thrown when the second child of the first grid element is expanded.

### Steps to reproduce  

1. Open /hierarchical-grid/hierarchical-grid-excel-style-filtering-sample-2
2. Expand first row w/ Artist name Naomi Yepes
3. On the child grid, expand the second child, specifically the one that has an Album name 'Dream Driven'
4. Observe the DevTools' console

### Result  
ERROR Error: InvalidPipeArgument: 'Unable to convert "Invalid Date" into a date' for pipe 'Re'

### Attachments  
![image](https://user-images.githubusercontent.com/8365193/67095840-90173b80-f1bf-11e9-9eb3-abc4236101de.png)

**Comment by MayaKirova** [comment]
@3phase I can no longer reproduce this. Seems to have been resolved in the meantime.

**Comment by 3phase** [comment]
@MayaKirova i can't reproduce it anymore either. Closing the issue.
