### ISSUE TITLE
Create sample that demonstrate how to access all grid data in custom summaries

### ISSUE THREAD

**Issue by ddincheva** [IgniteUI/igniteui-angular-samples#1552]
### Description  
Create sample that demonstrate how to access all grid data in custom summaries, for example perform some sorting of the result in some of the columns summaries based on other column.

**Comment by zdrawku** [comment]
Done - https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/summaries.html#custom-summaries-which-access-all-grid-data
