### ISSUE TITLE
Scrolling in the remote virtualization sample is not smooth

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular-samples#1555]
### Description  
Scrolling in the remote virtualization sample is not smooth.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/virtualization.html#remote-virtualization-demo
2. Scroll down using the mouse wheel.

### Result  
After you stop scrolling row data is changed couple of times before the correct rows are visualized.

### Expected result  
The remote virtualization scrolling should be smooth.

**Comment by MayaKirova** [comment]
Sample seems to have been moved here: https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/remote_data_operations.html#remote-virtualization-demo
