### ISSUE TITLE
Create demo for igx-select with header and footer templates

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular-samples#1571]
### Description  
 [feature](https://github.com/IgniteUI/igniteui-angular/issues/5911)

Current Demos Dev sample:
![image](https://user-images.githubusercontent.com/4296944/69948933-2fd32380-14f9-11ea-87b5-1f50322cfff2.png)

**Comment by DaniMarinov** [comment]
This is my proposal about the sample
![headerandfooter](https://user-images.githubusercontent.com/41998471/70225540-e2a0bd00-1757-11ea-8ee3-972205c5ac08.png)
