### ISSUE TITLE
Update Toolbar Styling Samples

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular-samples#1576]
After removing the button properties from the toolbar theme, a separate button theme should be added to the toolbar styling samples:
- src/app/grid-crm/grid-crm
- src/app/grid/grid-toolbar-style
- src/app/hierarchical-grid/hierarchical-grid-toolbar-style
-  src/app/tree-grid/tree-grid-toolbar-style

**Comment by simeonoff** [comment]
@DiyanDimitrov Should we close this?
