### ISSUE TITLE
Conditional formatting integration sample with igxGrid

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#1595]
### Description  
Enrich #1485 by adding conditional formatting options tab to the context menu.

### Expected result  
User to be able to set the following rules:

- Numeric
- [x] Data Bars
- [x] Color Scale
- [x] Top 10%
- [x] Duplicate values
- [x] Unique values
- [x] Empty values

- Text
- [x] Duplicate values
- [x] Unique values
- [x] Empty values

**Comment by zdrawku** [comment]
Done
