### ISSUE TITLE
Data Analysis Tool Sample

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#1607]
Create a demonstration Data Analysis Tool Sample using the igxGrid, with context menu and including:
- [x] Charts
- [x] Conditional Formatting
- [ ] Summaries
- [ ] Sparklines
- [x] Integration Directives
- [x] Topics

**Comment by zdrawku** [comment]
Closing that issue for now, if we decide to make any updates there we will log new requirements.
