### ISSUE TITLE
DragHandlers not visible with Dark Theme

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#1631]
### Description  
DragHandlers in Drag and Drop, Animations Demo are not visible with Dark Theme

### Steps to reproduce  

1. Go to [Drag and Drop Sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/drag_drop.html)
2. Navigate "Animations" Demo
3. Switch to Dark Theme

### Result  
DragHandlers are not visible

### Expected result  
DragHandlers are visible

**Comment by ChronosSF** [comment]
@radomirchev , closing this as @3phase logged it for all the drag&drop samples separately.
