### ISSUE TITLE
Enhance conditional styling in chart integrations sample

### ISSUE THREAD

**Issue by HristoP96** [IgniteUI/igniteui-angular-samples#1648]
Apply the following changes to the sample:

- Add clear format functionality
- Remove button rendering on right click
- Render data analysis button on scroll (horizontal and vertical), only when there is an active range selection
- Data analysis button should render only for active ranges
- On grid cell click deactivates all active ranges if present.
- Add support for editing of cells that are into a range with applied formatting (every cell edit should trigger formatting of the whole range, no matter if the range is active or not).

**Comment by zdrawku** [comment]
Done
