### ISSUE TITLE
Add "edit" feature to FinJS sample

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#1665]
## Description  
Consider option how to enhance the FinJS grid with "edit" option. 

1) Make "Contract" column editable with a dropdown editor
2) Make "Country" column editable with a default editor
3) Insert a "Last Updated" column between "Country" and "Open Price" columns. This "Last Updated" field will be editable through a date picker.
4) Hide/Show grouped columns

**Comment by StefanIvanov** [comment]
OK let's make the following changes to the sample:
- [ ] 
- [ ] 
- [ ]
