### ISSUE TITLE
Mixed styles on staging

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-samples#1669]
### Description  
On staging the old and new styles are applied for the components. The sample loads its respective styles, while the ThemingWidget works with an earlier version and brings older styles, which leads to a conflict.

### Result  
![тт](https://user-images.githubusercontent.com/14248932/72593485-c1fa8400-390d-11ea-9816-7ba396aaf016.png)

**Comment by ChronosSF** [comment]
Already fixed on staging
