### ISSUE TITLE
Theming Samples Not Loading

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular-samples#1675]
### Description  
The theming samples are not loading when an attempt is made to open them under igniteui-angular9.0.0-beta.3.

### Steps to reproduce  

1. Attempt to open /samples/theming/theme-chooser
2. Observe the DevTools' console

### Result  
An error `Cannot combine @Input decorators with query decorators` is thrown.

### Attachments  
![image](https://user-images.githubusercontent.com/8365193/72820739-138d7080-3c78-11ea-8660-1e65425e8b60.png)

**Comment by HristoP96** [comment]
@3phase  This issue is no more reproducible on both [staging](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/themes/examples.html) and [prod](https://www.infragistics.com/products/ignite-ui-angular/angular/components/themes/examples.html) -
