### ISSUE TITLE
The third Drag&Drop sample is missing

### ISSUE THREAD

**Issue by VMihalkov** [IgniteUI/igniteui-angular-samples#1710]
### Description  
The sample is missing.

### Steps to reproduce  

1. Open https://staging.infragistics.com/angularsite/components/drag_drop.html#demo-2
2. The sample is missing

### Result  
The sample is missing

### Expected result  
The samples should be present

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by MayaKirova** [comment]
Duplicate of #1708
