### ISSUE TITLE
Pinning button disappears from toolbar when pinning several columns in Edge

### ISSUE THREAD

**Issue by VMihalkov** [IgniteUI/igniteui-angular-samples#1711]
### Description  
Pinning button disappears from the toolbar when you pin 4 or 5 columns in Edge.

### Steps to reproduce  

1. Open https://infragistics.com/angularsite/components/grid/column_pinning.html
2. Click on the pinning button in the toolbar and select the first 4 columns

### Result  
The button disappears from the toolbar

### Expected result  
The button should not disappear

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![PinningButtonDisappear](https://user-images.githubusercontent.com/12252163/73522979-8209c580-4412-11ea-967f-17196650e8db.gif)

**Comment by MayaKirova** [comment]
This is not an issue in the sample. I've logged it in the main repo: https://github.com/IgniteUI/igniteui-angular/issues/6577
