### ISSUE TITLE
Chart integration enhancements for charts

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#1723]
### Description  
Implement the following:

1. Rotate the category label:
![image](https://user-images.githubusercontent.com/11193764/73657979-1175d980-469c-11ea-9407-1ad6100b7e4e.png)

2. Show %/ Values in the Pie Slice instead of label and legend with the same info
![image](https://user-images.githubusercontent.com/11193764/73658028-2b172100-469c-11ea-9cab-d0e7b46fcb21.png)

**Comment by HristoP96** [comment]
This issie is logged in dev azure/igniteui-angular, since it is regarding the extras package

**Comment by HristoP96** [comment]
This issue is fixed - dev azure/igniteui-angular PR # 2
