### ISSUE TITLE
Opening a modal dialog causes the whole page to scroll on Firefox

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular-samples#1728]
### Description  
Opening a modal dialog causes the whole page to scroll on Firefox

### Steps to reproduce  

1. Open the https://staging.infragistics.com/angularsite/components/grid/editing.html
2. Click Add New Product

### Result  
The whole page scrolls and cuts half the sample

### Expected result  
The page shouldn't scroll (or should scroll so that the sample is fully visible)

### Attachments  
![issue1](https://user-images.githubusercontent.com/2188411/73665436-c662c300-46a9-11ea-819c-98d0ed0ca525.gif)

**Comment by ddincheva** [comment]
This problem is addressed [here](https://github.com/IgniteUI/igniteui-angular-samples/issues/1728#event-3471608650)
