### ISSUE TITLE
Multiple Autocompletes in a single page rendering the first dropdown box in the html code.

### ISSUE THREAD

**Issue by Praxsr014** [IgniteUI/igniteui-angular-samples#1729]
### Description  
When implementing multiple Autocomplete elements that opens the dropdown on clicking the input box, no matter which input field is clicked only the dropdown box of the first input field is shown and after typing any text in the clicked input field, then the respective dropdown is shown while still showing the first input field's dropdown. 

- igniteui-angular version: 9.0.0-beta.3

- browser: Chrome for Windows

### Steps to reproduce  

1. Open https://stackblitz.com/edit/autocomplete-open-on-click-daccwk
2. Click on both the input fields for **Town** and **Town 1**
3. Type something in the **Town 1** input field

### Result  
What is the actual result after following the steps to reproduce?
Clicking on **Town 1** input field opens the dropdown of **Town**

### Expected result  
What is the expected result after following the steps to reproduce?
Clicking on **Town 1** should open its respective dropdown 

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/53585555/73666406-61d34400-4668-11ea-88e8-c44bb2840680.png)

**Comment by didimmova** [comment]
That's not an issue but a wrong implemented dropdown. If you use the [igxToggleAction] on the input group, instead of writing a function, it works perfectly fine.
