### ISSUE TITLE
Create a new demo demonstrating the grid editing capabilities

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-samples#1730]
Create a new demo demonstrating the grid editing capabilities in the context of real business scenario.

Version 1.0:
- [x] Data prepared
- [x] Editing control buttons added – cellEditing, rowEditing, none
- [x] Custom editors added (see Status and Priority fields)
- [x] Added editing validation ( see Started Date and Deadline columns)
- [x] Some business logic for the scenario (calculating progress, etc)
- [x] Details view added with:
- Description content (empty, but can be edited)
- Acceptance criteria checkboxes
- [x] Line chart to show progress. 
- [x] Added milestone filed to group by
- [x] Added Delayed status
- [x] Highlighting the Status column based on Stefan design.
- [x] Highlighting the Actual hours column, if value exceeds Estimation value.
- [x] Add / Delete capabilities. For Add there is a Create Issue button added, and Stefan’s design has a proposal for the Add dialog window. 
- [x] Template group row: New (count), In Progress (2), open chart for tasks
- [x] Fix bug with missing owner
- [x] Keep the detail view simple with only a progress bar
- [ ] Row selection - select N rows for edit, open them in dialog for edit IN PROGRESS Hristo
- [ ] Style the Create Issue dialog, move outlet in the template to be affected by the theme Hristo
- [ ] Applying proper css for the details view to look better. - Marin
- [ ] Master Backlog 
- Drag-and-drop
- Queue, Discovery.... labels for Master Backlog
- Tabs in Master backlog for filtering on labels
- editing in master backlog

TODO:
- [ ] search in Master backlog
- [ ] selection in master backlog to drag and drop multiple items
- [ ] Introduce labels and tags on tasks
- [ ] Action buttons columns
- [ ] Add comments textbox in detail view
- [ ] Property panel on the right, holding filtering
- [ ] Introduce dependencies between tasks, probably by assigning all tasks to a single parent (epic)
- [ ] The line chart in the details view needs to be redesigned to achieve a meaningful purpose. My initial idea was for the chart to display two lines:
- the ideal curve of progress based on started date, deadline and estimated hours.
- The extrapolated curve based on actual progress up to the current moment.
Bugs: Extrapolated curve may exceed the total estimated hours.
- [ ] Kanban view/card views instead of grid view
- [ ] Any business logic that will make the sample as reals as possible: charts to show  all tasks per employee, all tasks per team, highlight a task if the employee seems to be too busy with In progress tasks ( this will demonstrate some data analysis as in the Chart Integration sample).

**Comment by zdrawku** [comment]
@radomirchev after the last meeting we've decided to define acceptance criteria for Version 1, everything else remains part of the TO DO list and will be implemented later on for the upcoming versions. Feel free to update both lists and update us in order to address everything for the first version of the application.

**Comment by hanastasov** [comment]
Task moves to live as a standalone app: https://github.com/IgniteUI/TaskPlanner/issues
