### ISSUE TITLE
Button group text is bigger than its container element and gets chopped

### ISSUE THREAD

**Issue by sdimchevski** [IgniteUI/igniteui-angular-samples#1760]
### Description  
Button group text is bigger than its container element and gets chopped when Bootstrap Light or Bootstrap Dark theme is applied.

### Steps to reproduce  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/live_data.html
2. Apply a Bootstrap theme
3. Look at the button group above the grid

### Result  
Live All Prices button text and icon are chopped

### Expected result  
Live All Prices button text and icon should be visible when a Bootstrap theme is applied

### Attachments  
![btngroup](https://user-images.githubusercontent.com/15327632/74166111-b9584d80-4c2e-11ea-8f68-5959a49cb9f8.png)

**Comment by zdrawku** [comment]
@HristoP96 this is something that I thought of lately, we may think of adding this as a feature request and implement `ellipsis` of the text. I am adding this as a proposal for the next sprint in order to discuss it with @radomirchev

**Comment by sdimchevski** [comment]
There is a sample issue with the way the button labels are set in the code. For example the first two are written in capital letters - LIVE PRICES and LIVE ALL PRICES - and then we have the next two written like this - Stop and Chart.

The problem with the clipped Live All Prices button label is a component issue. It is a text overflow problem. It should display an ellipsis.

**Comment by hanastasov** [comment]
> There is a sample issue with the way the button labels are set in the code. For example the first two are written in capital letters - LIVE PRICES and LIVE ALL PRICES - and then we have the next two written like this - Stop and Chart.
> 
> The problem with the clipped Live All Prices button label is a component issue. It is a text overflow problem. It should display an ellipsis.

Issue is available regardless if bootstrap theme is applied, isnt it , @sdimchevski  ? Also, I don't see the relation if Capital letters are used. If you believe this is an issue with the component style in its core, please log a new issue in the igniteui-angular repo about it.
