### ISSUE TITLE
Sample doesn't update when a different theme is applied

### ISSUE THREAD

**Issue by sdimchevski** [IgniteUI/igniteui-angular-samples#1771]
### Description  
Sample doesn't update when a new theme or a setting is applied

### Steps to reproduce  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/card.html
2. Change the theme or apply a new colour
3. Look at the last sample

### Result  
The sample doesn't update

### Expected result  
The sample should update

### Attachments  
![sample](https://user-images.githubusercontent.com/15327632/74347664-192f2f80-4dba-11ea-91e5-3c18d931b837.jpg)

**Comment by didimmova** [comment]
It's expected behavior.
