### ISSUE TITLE
Toast message not visible when Bootstrap Light theme is applied

### ISSUE THREAD

**Issue by sdimchevski** [IgniteUI/igniteui-angular-samples#1792]
### Description  
Toast message not visible when Bootstrap Light theme is applied

### Steps to reproduce  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/toast.html
2. Apply Bootstrap Light theme
3. Click on Show Toast button and look at the message

### Result  
Toast message is not visible 

### Expected result  
Toast message should be visible

### Attachments  
![toast](https://user-images.githubusercontent.com/15327632/74667931-e2d42480-51ac-11ea-9428-645b6442a3ef.jpg)

**Comment by sdimchevski** [comment]
It's a component issue. The text is there but it's white and it's on a white background

**Comment by StefanIvanov** [comment]
@didimmova @sdimchevski  should this issue be closed now that the PR has been merged, or there is something else left to do for it?

**Comment by didimmova** [comment]
I don't think there's something else left to do.
