### ISSUE TITLE
[JP] Sample title is wrong

### ISSUE THREAD

**Issue by ymita** [IgniteUI/igniteui-angular-samples#1797]
### Description  
Sample title is wrong.

### Steps to reproduce  

1. Go to https://jp.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_editing.html
2. Observe the page title

### Result  
"Tree Grid 並び替え" is presented.

### Expected result  
"Grid 行編集" or something similar is presented.

### Attachments  
![image](https://user-images.githubusercontent.com/14340675/74712269-42900580-5269-11ea-9ca3-8e4b94f3659f.png)

**Comment by simeonoff** [comment]
@ymita Please log this under the [docfx repository](https://github.com/IgniteUI/igniteui-docfx)

**Comment by ymita** [comment]
@simeonoff Sure, I just did it. Thanks.
