### ISSUE TITLE
"Enable gestures" switch thumb is not visible when Fluent Dark theme is applied

### ISSUE THREAD

**Issue by sdimchevski** [IgniteUI/igniteui-angular-samples#1799]
### Description  
"Enable gestures" switch thumb is not visible when Fluent Dark theme is applied

### Steps to reproduce  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/navdrawer.html
2. Apply Fluent Dark theme
3. Look at the "Enable gestures" switch thumb

### Result  
"Enable gestures" switch thumb is not visible

### Expected result  
"Enable gestures" switch thumb should be visible

### Attachments  
![switch-thumb](https://user-images.githubusercontent.com/15327632/74739532-b201f700-5261-11ea-9817-b492eac07fe9.jpg)

**Comment by didimmova** [comment]
@simeonoff this issue is no longer an issue because after refactoring this sample isn't in the topic anymore.
