### ISSUE TITLE
Colors in Navbar Demo don't update when a Bootstrap theme is applied

### ISSUE THREAD

**Issue by sdimchevski** [IgniteUI/igniteui-angular-samples#1800]
### Description  
Colors in Navbar Demo don't update when a Bootstrap theme is applied

### Steps to reproduce  

1. Open https://staging.infragistics.com/products/ignite-ui-angular/angular/components/navbar.html
2. Choose a Bootstrap theme
3. Change the primary color for example

### Result  
Colors don't update

### Expected result  
Colors should update

**Comment by simeonoff** [comment]
The navbar uses the surface color as its background. Closing as this is by design.
