### ISSUE TITLE
igx-grid - Global string filter fails when a date columns exists

### ISSUE THREAD

**Issue by lalo-mx** [IgniteUI/igniteui-angular-samples#1959]
## Description  
Global string filter fails when a date columns exists

 * igniteui-angular version:  9.0.1
 * browser: Chrome 81.0.4044.129

## Steps to reproduce  

1. Run sample [angular-pcp6jp.zip](https://github.com/IgniteUI/igniteui-angular/files/4576991/angular-pcp6jp.zip)
 (https://stackblitz.com/edit/angular-pcp6jp)
2. Set "Insurance" value in Search field.
3. Click on "Exact Match" button.
4. Click on filtering field on "Date" column.
5. Close dialog
6. Try to open the filtering field on "Date" column.
 
## Result  

- An error is shown in the console:
ERROR
 Error: e.expression.searchVal.toDateString is not a function
 ERROR
 Error: Cannot read property 'searchInput' of undefined

- The fitering field can not be opened twice.

## Expected result  
The filtering expression is parsed if possible to date, o the filtering expression is ignored for date columns.

**Comment by zdrawku** [comment]
hm, It looks like [the sample that we provide](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/search.html#demo) is different (and working fine) and you've built a whole new scenario based on it. In that case could you please consider my comments above and update your sample to comply with the FilterinOperand conditions in order to limit problems like the one that you've mentioned.

**Comment by lalo-mx** [comment]
Yes, @zdrawku  it is  not the original sample, i will consider the comments but i still think that the global filter should consider the dataType of the columns o the applied condition.  So is the described scenario working as expected?

**Comment by lalo-mx** [comment]
**Workaround:**
I changed the filterGlobal for a custom filteringExpressionsTree and is working now.

Working sample https://stackblitz.com/edit/angular-pcp6jp-hqcmaf

**Comment by DiyanDimitrov** [comment]
@lalo-mx, The global filter is just using the operand that you provide. If you provide a string operand we cannot replace it. You could implement your own operand which handles different data types. The approach that you use in your workaround is also a valid one.
