### ISSUE TITLE
In sample Grid Remote Data Operations  when scroll down and click on a cell the scroll is moved to the beginning

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular-samples#1987]
### Description  
In sample Grid Remote Data Operations  when scroll down and click on a cell the scroll is moved to the beginning

### Steps to reproduce  

1. Open [sample](https://www.infragistics.com//angularsite/components/grid/remote_data_operations.html)
2. Scroll down the grid
3. Click on a cell

### Result  
Scroll is moved to the beginning and the first grid cell is selected

### Expected result  
Scroll should not be changed and the clicked cell should be selected

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by 3phase** [comment]
@nrobakova, I think that that issue is not a sample one. It affects all samples w/ remote virtualization and it's most likely caused by a newly introduced focus handler. I have logged it here IgniteUI/igniteui-angular#7388. 
I will close that issue. Please, re-open if I'm mistaken.
