### ISSUE TITLE
FinJS' dark theme would apply on other samples as well

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular-samples#2023]
### Description  
The FinJS sample's dark theme applies on other samples as well.

### Steps to reproduce  

1. Open /finjs-sample
2. Toggle Dark theme
3. Open another sample and observe that the dark theme from the FinJS sample has been transferred to the newly opened sample as well.

### Result  
Theme was applied on the other sample

### Expected result  
The dark theme switch button in the FinJS sample should be concerning only the FinJS sample and should not be applying its theme to the other samples as well.

**Comment by HristoP96** [comment]
This behavior is reproducible only in the samples browser and the behavior is considered expected, so I will close this issue
