### ISSUE TITLE
Grid templating filter cell sample does not allow focusing the filter input.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular-samples#2036]
### Description  
Grid templating filter cell sample does not allow focusing the filter input.

### Steps to reproduce  

1. Go to sample at: 
https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/filtering.html#retemplating-filter-cell

2. Click on a input in the filter template.
3. Focus does not go in the input so you cannot type in a new value.

### Result  
Header cell appears to take the focus so you cannot type in the input.

### Expected result  
Clicking on the input should allow typing new values. Currently you can only enter values if you click on the search icon.

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by nrobakova** [comment]
This issue is similar to #2021

**Comment by zdrawku** [comment]
Fixed
