### ISSUE TITLE
input group samples difference between docfx and stackblitz

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular-samples#2055]
### Description  
The difference comes from the theme as it is not stored in the stackblitz sample.
As we override the type of the input through the **theme**, in docfx some inputs do not look as they ought to. For instance, **bootstrap** does not have any **line** type input and **material** does not introduce any **box** or **boostrap** type inputs.

### Steps to reproduce  
1. Navigate to the [input group](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/input_group.html) sample.

Possible solutions:
1. We may remove that sample and embed screenshots of every input type.
2. We may note that the theme is not stored in the stackblitz sample, so the users could face differences between the docfx and stackblitz samples(this note may be placed somewhere in the theming widget e.g. header or footer)

![MicrosoftTeams-image](https://user-images.githubusercontent.com/7037740/83391509-3e44be00-a3fc-11ea-9887-9c867d901596.png)
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/7037740/83391510-3f75eb00-a3fc-11ea-86a9-384a12ec3ea7.png)

**Comment by SisIvanova** [comment]
There is no longer any difference between docfx and stackblitz after the input group sample was refactored. https://github.com/IgniteUI/igniteui-angular-samples/pull/2204
