### ISSUE TITLE
Sample for grid-multiple-row-drag does not work in IE11

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular-samples#2080]
### Description  
Sample for grid-multiple-row-drag does not work in IE11

### Steps to reproduce  

1. Open [samle](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_drag.html#configuration) (the sample grid-multiple-row-drag ) in IE11
2. Try to drag a row

### Result  
 Row is not moved in the other grid and an error is previewed

### Expected result  
Row should be moved without errors

### Attachments  
![image](https://user-images.githubusercontent.com/11463104/84145314-56eb4e80-aa62-11ea-83d4-e6f3884ae191.png)

**Comment by Lipata** [comment]
Already fixed
