### ISSUE TITLE
Drag & Drop Kanban sample throws an error

### ISSUE THREAD

**Issue by mmart1n** [IgniteUI/igniteui-angular-samples#2087]
### Description
A "cannot set property 'hide' of null" error is thrown when dragging a card and dropping it in the same column. (See Attachments)

### Steps to reproduce  

1. Open the Kanban sample
2. Start dragging a card
3. Drop it in the same column

### Result  
An error is thrown

### Expected result  
No errors to be thrown

### Attachments  
![kanbansample](https://user-images.githubusercontent.com/44684385/84397976-044b9700-ac08-11ea-815a-94ff7deeb1d2.gif)

**Comment by kdinev** [comment]
@skrustev
