### ISSUE TITLE
Radio button alignment in checkbox demo

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular-samples#21]
### Description  
The radio buttons in the checkbox demo article are aligned opposite from the rest of the inputs in the form.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/checkbox.html 
2. Go to "Label and Input components"
3. Notice the gender radio buttons

### Result  
Everything in the form is left aligned, except for the radio buttons.

### Expected result  
The radio buttons should also be left aligned.

### Attachments  
![image](https://user-images.githubusercontent.com/1472513/33274937-20c6f60c-d39a-11e7-85f9-33dab5a708e0.png)

**Comment by SlavUI** [comment]
Issue is resolved
