### ISSUE TITLE
Add FAB to the Display Density section sample

### ISSUE THREAD

**Issue by StefanIvanov** [IgniteUI/igniteui-angular-samples#2117]
### Description  
I was investigating today if FAB was supporting Display Density and saw that the respective [sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/button.html#display-density) did not contain one so I had to add it in Stackblitz. Please update the sample by adding a FAB next to the other three.

**Comment by simeonoff** [comment]
@SisIvanova also add the extended version of the FAB button to this sample.
