### ISSUE TITLE
Column Pinning Sample's Action Toolbar Text is Not Visible

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular-samples#2138]
### Description  
When a dark theme is applied on the column pinning sample, the text inside the action toolbar is not visible.

### Steps to reproduce  

1. Open the first column pinning sample in the staging environment of our product
2. Switch the current theme to one of the dark themes
3. Expand the action toolbar and observe the text

### Result  
The text is not visible

### Expected result  
The text should be colored in the contrast color of the background

### Attachments  
![image](https://user-images.githubusercontent.com/8365193/88148879-eeb68d80-cc07-11ea-8055-1dbf97f06d67.png)

**Comment by VMihalkov** [comment]
It looks like the issue is no longer reproducible on staging

**Comment by 3phase** [comment]
I am closing the issue, ever since it's not relevant anymore.
