### ISSUE TITLE
Main editing sample update

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#2183]
### Description  
One of our most visited topics is the [Editing topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing.html). Let's think of a possible sample update, to re-fresh it a little bit.

**Comment by Lipata** [comment]
Note that previous Milestone we've done [this editing event improvements](https://github.com/IgniteUI/trial-watermark/issues/46) and in this Milestone, we've further improved them and [added new editing events](https://github.com/IgniteUI/trial-watermark/issues/47). Both epic items contains all the information related to implementation, samples, and documentation and in the second feature, you can see that there are 2 new improvements suggested.
