### ISSUE TITLE
Hierarchical Grid's Virtualization and Performance sample won't open neither in Codesandbox, nor in Stackblitz

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular-samples#2213]
### Description  
The Virtualization and Performance sample won't load in Codesandbox, failing with error `Expected 'styles' to be an array of strings.`, while the Stackblitz button is grayed out and cannot be opened at all.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/hierarchicalgrid/virtualization.html
2. Try to open the first sample in Codesandbox

### Result  
Loading fails w/ the error, mentioned above

**Comment by HristoP96** [comment]
It seems that codesandbox cannot handle empty lines in in empty scss files, removing the empty line in the corresponfing scss file will fix the issue
