### ISSUE TITLE
Some chart samples are not working in production

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular-samples#2257]
### Description  
The samples that are not loading in production, are the following:
 - https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart.html
 - https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-type-scatter-contour-series.html
 - https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-type-stacked-spline-area-series.html
 - https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-type-stacked-100-spline-area-series.html
 - https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-type-scatter-area-series.html
 - https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-navigation.html
 - https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-synchronization.html
 - https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-titles.html
 - https://www.infragistics.com/products/ignite-ui-angular/angular/components/data-chart-value-overlay.html

**Comment by zdrawku** [comment]
Addressed with production build - 2020.9.29.2
