### ISSUE TITLE
IgxGrid stackblitz samples do not work under Edge

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-samples#226]
![38918236-c4be77e2-42f5-11e8-9cfc-b438e0211e11](https://user-images.githubusercontent.com/14248932/39040003-33a5495c-448f-11e8-95b5-25ca4070efd2.PNG)

**Comment by tiliev** [comment]
After testing it's been determined this is a third-party issue which is fixed in the latest Edge version:
![capture](https://user-images.githubusercontent.com/6439482/39042788-6669b85a-4494-11e8-86ef-b5ab253c4333.PNG)
