### ISSUE TITLE
Pie Chart samples cannot be opened in StackBlitz

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular-samples#2261]
### Description  
When I'm trying to open some samples from the [Angular Pie Chart Overview](https://www.infragistics.com/products/ignite-ui-angular/angular/components/pie-chart.html) topic in StackBlitz by clicking on the button,  "Uncaught TypeError: i is undefined" error is thrown in the console and the StackBlitz is not opening.

### Steps to reproduce  

1. Open [this](https://www.infragistics.com/products/ignite-ui-angular/angular/components/pie-chart.html) topic
2. Click on the "View on StackBlitz" button below the first demo

### Result  
StackBlitz window is not opened and an error could be found in the console.

### Expected result  
Open and run the demo.

**Comment by dobromirts** [comment]
Hey @teodosiah , 
This issue is no more reproducible on both staging and prod. Are you still having the issue with these samples?
