### ISSUE TITLE
igxGrid cell editing sample issues

### ISSUE THREAD

**Issue by Lipata** [IgniteUI/igniteui-angular-samples#2264]
### Description  
Open the [igxGrid cell editing sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell_editing.html)

### Steps to reproduce 1

1. In the first grid, open a cell from 'Available at' column (choose the third row), and select one additional value '14/22':

![image](https://user-images.githubusercontent.com/2621802/94894119-65d29280-0491-11eb-84c8-5cfd6861eaa4.png)
 
2. Press Enter to choose the value and choose Enter to submit the value.
3. Open the same cell for editing 

### Result  
The '14/22' value is not selected in the combo. If it is selected again, the grid cell value has twice '14/22'.
![image](https://user-images.githubusercontent.com/2621802/94894344-d5e11880-0491-11eb-986a-634d7c4b27ae.png)

### Expected result  
The '14/22' value should be selected in the combo.

### Steps to reproduce 2

1. In the first grid, open a cell from 'Available at' column (choose а cell that has more than one value), and deselect one of the selected values in the combo.
2. Press enter to close the combo.
3. Press enter to submit the new value.

### Result  
Note that several of the other cells' values, in the same 'Available at' column, are changed.

### Expected result 

Other cell's value should not be changed or at least if this is ok the behavior should be described.

**Comment by zdrawku** [comment]
Fixed https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing
