### ISSUE TITLE
Create Add Row Tree Grid Samples

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular-samples#2269]
- [ ] Sample deriving from the Row Editing sample showing default native row adding UI for tree grid without transactions.
    - specifically show conditional "add child" visibility in the action strip template (such as hide it if the row's level is more than 2)
- [ ] Sample deriving from the first one showing custom styling of all UI elements
    - the styling of the edit UI can be taken from the Row Editing styling sample
    - some styling can be applied to the icons in the action strip
    - some other styling can be applied to the unfiled values (column headers) text

**Comment by zdrawku** [comment]
Done
