### ISSUE TITLE
Root level summaries are not visible in one of grid's summaries samples

### ISSUE THREAD

**Issue by VMihalkov** [IgniteUI/igniteui-angular-samples#2304]
### Description  
The grid's height is too big and the root level summaries are not visible.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/summaries.html#demo-1
2. At the top click on "Root level only" or "Root and child" to make sure the root level summaries are enabled
3. Scroll to the bottom of the grid

### Result  
The root level summaries are not visible

### Expected result  
The root level summaries are visible

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by dobromirts** [comment]
This issue is no more reproducible on both staging and prod.
