### ISSUE TITLE
Selection template numbering sample not working

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular-samples#2307]
### Description  
The selection template numbering sample in our staging environment seems freezed after loading the first record, throwing the following error in the console:

`ERROR Error: InvalidPipeArgument: 'Berlin is not a number' for pipe 'e'`

### Steps to reproduce  

1. Open [Selection Template Numbering](https://staging.infragistics.com/angular-demos/grid/grid-selection-template-numbering) sample (same goes for [Excel-style selection template](https://staging.infragistics.com/angular-demos/grid/grid-selection-template-excel) and [Conditional row selectors](https://staging.infragistics.com/angular-demos/grid/grid-conditional-row-selectors))
2. Open the console and observe the errors

**Comment by dobromirts** [comment]
@3phase This issue is no more reproducible on both staging and prod, so I will close the issue.
