### ISSUE TITLE
Improve Angular Landing page loading time

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#2328]
Improve loading time of marketing page of Ignite UI for Angular

**Comment by zdrawku** [comment]
@kdinev made the initial changes - [related branch](https://github.com/IgniteUI/igniteui-angular-samples/tree/crm-grid-enh). We will pick up from here

**Comment by zdrawku** [comment]
@hanastasov, please keep in mind the workflow for the app-lob samples https://github.com/IgniteUI/igniteui-angular-samples/blob/master/.github/workflows/build-app-lob.yml#L31

**Comment by zdrawku** [comment]
Next week all changes will be promoted to production as well.
Current state: 
(PRODUCTION)
![image](https://user-images.githubusercontent.com/11193764/100349418-191eba00-2ff1-11eb-9210-e80c4365f05c.png)

(STAGING)
![image](https://user-images.githubusercontent.com/11193764/100349481-3489c500-2ff1-11eb-9bf5-5d970180df12.png)

**Comment by hanastasov** [comment]
The current report:
[staging.infragistics.com-20201126T140601.html.zip](https://github.com/IgniteUI/igniteui-angular-samples/files/5602873/staging.infragistics.com-20201126T140601.html.zip)

**Comment by hanastasov** [comment]
https://www.infragistics.com/angular-demos-grid-crm/grid-crm
