### ISSUE TITLE
Row selection - Row numbering demo, Excel Style Row Selectors demo and Conditional Selection demo does not load correctly on staging

### ISSUE THREAD

**Issue by mddragnev** [IgniteUI/igniteui-angular-samples#2335]
## Description  
All three demos do not load correctly and throw error. Might be a sample issue.

 * igniteui-angular version: 10.2
 * browser: All browsers

## Steps to reproduce  

1. Open https://staging7.infragistics.com/products/ignite-ui-angular/angular/components/grid/row_selection.html
2. Scroll down to Row numbering demo, Excel Style Row Selectors demo and Conditional Selection demo

## Result  
Observe that only 1 record is rendered and an error is thrown in the console

## Expected result  
The sample should load normally as in production.

**Comment by dobromirts** [comment]
@mddragnev This issue is no more reproducible on both staging and prod, so I will close the issue.
