### ISSUE TITLE
Toolbar dropdown background font

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#2349]
### Description  
 After theme is changed through the theming widget, the background font of the toolbar for column pining and hiding disappears. 

### Steps to reproduce  

1. Open staging samples:
https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/column-pinning
https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/column-hiding
2. Changed theme
3. Open the dropdown menu

### Result  
![C Hiding Issue](https://user-images.githubusercontent.com/52001020/98808162-65300300-2424-11eb-94b9-40f81a1913ee.gif)

**Comment by ChronosSF** [comment]
resolved with TAAS update
