### ISSUE TITLE
Grid's Summary sample doesn't work in stackblitz

### ISSUE THREAD

**Issue by sstoyanovIG** [IgniteUI/igniteui-angular-samples#235]
### Description  
Grid's Summary sample doesn't work in stackblitz. It seems like that the IgxSwitchModule is not imported

### Steps to reproduce  

1. Open https://stackblitz.com/angular/qdnbrokrnoe?file=app%2Fgrid%2Fgrid-sample-3%2Fgrid-sample-3.component.ts

### Result  
There is an error

### Expected result  
Working sample

**Comment by zdrawku** [comment]
This issue is not relevant anymore, we've removed all switch components. Now there would be Summary icon to toggle the active state. 

Related PR:
https://github.com/IgniteUI/igniteui-angular-samples/pull/238
