### ISSUE TITLE
Calendar angular samples are not loaded in code view

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#2385]
- [x] Both samples under Views section are not loaded in Code View:
1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/calendar#views
2. See the result:
![image](https://user-images.githubusercontent.com/11193764/100466174-2adb8c80-30d9-11eb-87f8-db062f227751.png)

The "View in full screen button" is working fine.

- [x] Toggle sample is also not loaded - 
https://www.infragistics.com/products/ignite-ui-angular/angular/components/toggle

**Comment by zdrawku** [comment]
working on [staging](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/calendar#views) will be closed after docfx-template upgrade

**Comment by HristoP96** [comment]
The fix is [live](https://www.infragistics.com/products/ignite-ui-angular/angular/components/calendar#views) now
