### ISSUE TITLE
Some samples for charts doesn't work in stackblitz

### ISSUE THREAD

**Issue by sstoyanovIG** [IgniteUI/igniteui-angular-samples#239]
### Description  
Some samples for charts doesn't work in stackblitz or the stackblitz button doesn't work

Stackblitz button doesn't work for:

http://localhost:3000/components/categorychart_configuration_options.html
http://localhost:3000/components/categorychart_explore_chart_types.html
http://localhost:3000/components/financialchart_explore_chart_types.html
http://localhost:3000/components/financialchart_real_time_data.html
http://localhost:3000/components/financialchart_high_volume_data.html
http://localhost:3000/components/financialchart_configuration_options.html
http://localhost:3000/components/financialchart_custom_indicators.html

There is error when loaded in stackblitz:

http://localhost:3000/components/financialchart.html
http://localhost:3000/components/financialchart_performance.html

There is no sample loaded:

http://localhost:3000/components/financialchart_panes.html

**Comment by mharrington622** [comment]
Fixed with PR #251
