### ISSUE TITLE
Update grid sample not to show scrollbars on certain screen resolutions

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#24]
### Description  
Open https://www.infragistics.com/products/ignite-ui-angular, scrollbars appear on certain resolutions:

![image](https://user-images.githubusercontent.com/11193764/33550881-28c8e262-d8f8-11e7-8e6e-82184a729d3d.png)

**Comment by jberes** [comment]
The issue is still on the sample browser:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html

**Comment by kdinev** [comment]
@jberes Waiting on @simeonoff to finish another improvement in the docfx to request deployment.

**Comment by SlavUI** [comment]
@jberes the issue has been resolved and pushed to production :)
