### ISSUE TITLE
Auto fill in the Code View

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#2407]
### Description  
Some of the Angular samples have big empty spaces in the Code View like [toolbar](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/toolbar) and [column groups](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/collapsible-column-groups). The psace should be automatically filled in.

Example: 
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/52001020/101626452-ad434500-3a25-11eb-92b6-0eb616643204.png)

Test the solution with zoom in/out of the browser and OS.

**Comment by zdrawku** [comment]
@dobromirts, [some of the samples](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column-pinning) are already changed to fit the code-view container, example:
![image](https://user-images.githubusercontent.com/11193764/101775263-e0560900-3af7-11eb-80bf-c02f7aee9e2b.png)

We just need to apply this to all other grid samples
