### ISSUE TITLE
Elevations sample doesn't work in Stackblitz

### ISSUE THREAD

**Issue by SisIvanova** [IgniteUI/igniteui-angular-samples#2423]
### Description  
The elevations sample in the Shadows Topic doesn't work in Stackblitz although it is working in Codesandbox.

### Steps to reproduce  

1. Open shadows topic - https://www.infragistics.com/products/ignite-ui-angular/angular/components/shadows
2. Go to "How to add elevations?" section
3. Open the elevations sample in Stackblitz - https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/theming/card-sample-shadow

### Result  
There is an error: "Error in turbo_modules/igniteui-angular@11.0.9/lib/core/styles/themes/_index.scss (7:9)"

### Expected result  
The sample should work properly in both Stackblitz and Codesandbox.

### Attachments  
<img width="442" alt="Screen Shot 2021-01-08 at 1 49 03 PM" src="https://user-images.githubusercontent.com/59446295/104012351-5497d100-51b8-11eb-83e0-b9622a7b0a30.png">

**Comment by zdrawku** [comment]
There is no such topic anymore, and after testing all card samples part of the card topic, everything looks fine
