### ISSUE TITLE
`columnPinning`, `toolbarTitle` are deprecated

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#2431]
Some samples are not migrated to the new toolbar.
Example [StackBlitz](https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos/grid/grid-sample-toolbar-pinning) part of https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/column-pinning

**Comment by wnvko** [comment]
[Grid Advanced Filtering](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/advanced-filtering) topic is also not updated. This is shown in [Usage](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/advanced-filtering#usage) section:
```
<igx-grid [data]="data" [autoGenerate]="true" [showToolbar]="true" [allowAdvancedFiltering]="true">
</igx-grid>
```
