### ISSUE TITLE
Make header icon behavior consistent in samples

### ISSUE THREAD

**Issue by SDinev** [IgniteUI/igniteui-angular-samples#244]
### Description  
On hover, the icon should behave in the same way. 

### Attachments  
Default behavior with filtering, as seen in the product:
<img width="160" alt="screen shot 2018-04-20 at 16 51 12" src="https://user-images.githubusercontent.com/13866657/39054818-4f2362e6-44bb-11e8-98b2-e0c2a1833936.png">

Pinning currently:
<img width="251" alt="screen shot 2018-04-20 at 16 51 26" src="https://user-images.githubusercontent.com/13866657/39054819-4f44e038-44bb-11e8-9efc-28b6364c1a39.png">

Summaries currently:
<img width="238" alt="screen shot 2018-04-20 at 16 51 35" src="https://user-images.githubusercontent.com/13866657/39054821-4f6220b2-44bb-11e8-8a33-5219b13e7239.png">

**Comment by zdrawku** [comment]
This is something that is not going to be added to the samples now, we are going to wait for Data Operations UI creation.
