### ISSUE TITLE
Modify igxTreeGrid Row Selection sample in order to add cascading selection

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular-samples#2454]
### Description  
Modify the existing [igxTreeGrid Row Selection sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/row-selection) so that an option for the [new multiple cascade selection](https://github.com/IgniteUI/igniteui-angular/issues/8040) is added.

- add button in the button group for cascade mode
- add snackbar message corresponding to the new mode

**Comment by zdrawku** [comment]
Done and available here https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/row-selection#cascade-selection
