### ISSUE TITLE
The demos in igxGrid and igxTreeGrid State Persistence topics are throwing errors

### ISSUE THREAD

**Issue by teodosiah** [IgniteUI/igniteui-angular-samples#2466]
### Description  
The demos in igxGrid and igxTreeGrid State Persistence topics are throwing errors

### Steps to reproduce  

1. Open the [Grid State Persistence](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/state-persistence) and [Tree Grid State Persistence](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/state-persistence) topics 
2. Open the demos in StackBlitz.

### Result  
In igxGrid sample: ERROR
Error: Uncaught (in promise): Error: No component factory found for GridSaveStateComponent. Did you add it to @NgModule.entryComponents?
Error: No component factory found for GridSaveStateComponent. Did you add it to @NgModule.entryComponents?
at noComponentFactoryError

In igxTreeGrid sample: Error in src/app/app.module.ts (27:1)
',' expected.

### Expected result  
Running the samples successfully.

### Attachments  
Fixed demos could be found in the following links:
igxGrid - [https://stackblitz.com/edit/igx-grid-state-persistence-fix-sample?file=src/app/app.module.ts](https://stackblitz.com/edit/igx-grid-state-persistence-fix-sample?file=src/app/app.module.ts)
igxTreeGrid - [https://stackblitz.com/edit/igx-tree-grid-state-persistence-fix-sample?file=src/app/app.module.ts](https://stackblitz.com/edit/igx-tree-grid-state-persistence-fix-sample?file=src/app/app.module.ts)

**Comment by gedinakova** [comment]
This is now resolved with the fix for the duplicate issue #2643.
