### ISSUE TITLE
Financial Chart Demo should include data for days

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-angular-samples#247]
The Financial Chart Demo appears to include data values for every other month, this sample should include data points for days not bi-monthly as this data does not look good when selecting 1M 3M options from the toolbar

### Steps to reproduce  
1. open page: https://staging.infragistics.local/help/wpf/financial-chart-overview
2. Select 1M from toolbar 

### Result  
Only one data point is displayed

### Expected result  
Data points more accurately reflect the range selected and show multiple data points

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by HUSSAR-mtrela** [comment]
@IGvaleries this links points to WPF help docs. Did you mean Angular help docs?

**Comment by IGvaleries** [comment]
opps wrong link should be (https://staging.infragistics.local/products/ignite-ui-angular/angular/components/financialchart.html)

**Comment by HUSSAR-mtrela** [comment]
@IGvaleries this issue should be fixed now.
