### ISSUE TITLE
Batch editing sample is confusing

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular-samples#2476]
### Description  
There's an additional empty component in the grid with transactions sample and I'm confused, whether this is the way I'm supposed to define grids with transactions.

### Steps to reproduce  

1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/batch-editing
2. Check the html template
3. There's an `<app-grid-with-transactions>` component. This component is missing from the code example and without it transactions aren't turned on.

### Result  
Users cannot easily configure grids with transactions.

### Expected result  
Users should be able to get a complete example from the first sample they reach.

### Attachments  
N/A

**Comment by kdinev** [comment]
The dummy component wrapper is still present in the samples and when looking at the code example from the documentation, it's still not clear how to provide the correct transaction service.

For reference: https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/batch-editing

**Comment by damyanpetev** [comment]
@kdinev  An somewhat unfortunate combination in those samples I suppose, but they do use a second grid in the dialog that shows the changes to commit. So providing on the sample component level will definitely apply to both grids and can cause crosstalk. The wrapper is to isolate the two and the prudent thing I suppose was to provide once where needed, but I do agree that kind of hides it in the main sample tabs, when it should be one of the main bits to see.
Could be done by wrapping the dialog instead (w/ secondary provider) or changing the design to anything else that doesn't use a grid for it.

PS: If we can only show code for one component, should we actively avoid creating samples that use two or more for that reason?

**Comment by kdinev** [comment]
@damyanpetev The second grid is a grid which is not editable, so it doesn't matter whether you provide a transaction service to it or not?

**Comment by ViktorSlavov** [comment]
I'll start updating the topics according to the changes that will come w/ [the transaction refactor PR](https://github.com/IgniteUI/igniteui-angular/pull/9836)
