### ISSUE TITLE
Height of Financial Chart Demo should be increased so that multiple indicators can be added

### ISSUE THREAD

**Issue by IGvaleries** [IgniteUI/igniteui-angular-samples#248]
### Description  
The Financial Chart Demo price pane is no longer displayed after adding 2 financial indicators, as this is the first sample displayed, it should allow enough room to add multiple indicators without losing the price pane

### Steps to reproduce  
1. go to Financial Chart Demo (https://staging.infragistics.local/products/ignite-ui-angular/angular/components/financialchart.html) 
2. add two indicators to the chart

### Result  
price pane is no longer displayed 

### Expected result  
price pane is still displayed 

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by HUSSAR-mtrela** [comment]
actually this issue is in angular docs and not samples because the sample has 100% height

**Comment by HUSSAR-mtrela** [comment]
this is a known issue in the chart and increasing height of chart container will not fix this issue
