### ISSUE TITLE
Design for igxTree sample(s)

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular-samples#2500]
### Description  

1. We should determine how many samples are we going to create for the upcoming igxTree topic. 
2. Create design for these samples.
 

[igxTree Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Tree-Specification)

**Comment by StefanIvanov** [comment]
[samples design](https://share.goabstract.com/21717d0d-ab32-441e-bf9d-d4f691b7bac4)
