### ISSUE TITLE
The input group sample with the types of inputs hides the search type input

### ISSUE THREAD

**Issue by kdinev** [IgniteUI/igniteui-angular-samples#2566]
### Description  
Currently, when the sample is loaded in the SB, only 4 types of inputs are visible (there's a scrollbar, but it's not very obvious there's more). Please increase the height of the sample container to show all types without a scrollbar.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/input-group#input-types--input-group-type-token

**Comment by simeonoff** [comment]
Fixed with #2582
