### ISSUE TITLE
Tree grid finjs group by - stackblitz is not working

### ISSUE THREAD

**Issue by igdmdimitrov** [IgniteUI/igniteui-angular-samples#2568]
### Description  
Tree grid finjs group stackblitz is not working

### Steps to reproduce  
1. Open [stackblitz sample](https://stackblitz.com/github/IgniteUI/igniteui-live-editing-samples/tree/master/angular-demos-lob/treegrid-finjs?file=src%2Fapp%2Ftreegrid-finjs%2Ftree-grid-grouping.pipe.ts) or navigate from [tree grid group by](https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/groupby)

### Result  
Compiler error

### Expected result  
Sample should be working without errors

**Comment by DiyanDimitrov** [comment]
Please create a PR for master as well.
