### ISSUE TITLE
Grid's header in Paging sample changes its height during horizontal scrolling

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular-samples#258]
### Description  
During horizontal scrolling, once the first column goes out of view, the header's height is decreased and the whole grid shifts slightly up.

### Steps to reproduce  

1. Navigate to Paging sample
https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid_paging.html
2. Drag the grid's horizontal thumb right.

### Result  
As the first column goes out of view, the header's height is decreased and the whole grid shifts slightly up.

### Expected result  
The header's height should not change.

Note: Seems similar to https://github.com/IgniteUI/igniteui-angular/issues/1067 , but filtering is not enabled for this sample.

**Comment by hanastasov** [comment]
Issue does not reproduce anymore.
