### ISSUE TITLE
Grid example ehancements

### ISSUE THREAD

**Issue by SDinev** [IgniteUI/igniteui-angular-samples#26]
- [ ] All instance of the fuchsia color to be changed with byzantium. 
 This concerns - selected grid cell, toggle, active filter input, active sorting icon, progress bar color.
 - [x] Highlight color for places 1, 2 & 3 to become #FCF1FB
 - [x] The cup icons for places 1, 2 & 3 to be changed with attached SVG images with gold, silver and bronze. 
[trophy-icons-grid.zip](https://github.com/IgniteUI/igniteui-angular-samples/files/1526975/trophy-icons-grid.zip)
Important - the SVGs should be 20x20 px. The icon container should generally be 24x24 px, with the icon centered vertically and horizontally.
 - [x] Text in number cells should always be aligned right. Header text above such cells should also be aligned right.
 - [x] In the 'Top Speed' column, make sure there are always the same number of symbols after the '.' -- currently it would display '5.1', but '5'. It should be '5.0' so alignment doesn't break.
 - [x] Some flags and country names are currently mismatched. There's an issue logged in the IgniteUI/DocFX repository about this. https://github.com/IgniteUI/igniteui-docfx/issues/19 
 - [x] Make male names match with male avatars, and female names with female avatars

**Comment by SlavUI** [comment]
@SDinev i suggest for us to start doing those after the story's for the Demos are completed :)

**Comment by SDinev** [comment]
@SlavUI, the last three points are important, because they are functional issues that concern usability. 
They will also be used in a landing page demo, which will most probably be live end of this week and will be heavily advertised.

**Comment by SlavUI** [comment]
@SDinev Zdravko will try to update at least the last three points today ;)

**Comment by zdrawku** [comment]
Close after merge of https://github.com/IgniteUI/igniteui-angular-samples/pull/28

About point one, we are currently implementing changes in relation to the style structure, this point would be covered later.
