### ISSUE TITLE
Buttons inside Advanced Filtering Styling demo are not styled

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular-samples#2620]
### Description  
After [this bug](https://github.com/IgniteUI/igniteui-angular/issues/9382) is fixed, we should add different styles for the different button types.

### Steps to reproduce  

1. Open the Advanced Filtering Styling demo.
2. Open the advanced filtering.

### Result  
The buttons are not styled.

### Expected result  
The buttons should be styled.

### Attachments  
![image](https://user-images.githubusercontent.com/43128948/115578081-a11d9d00-a2cd-11eb-826a-0ad152262696.png)

**Comment by gedinakova** [comment]
We will review this again after the changes in the next major version.
