### ISSUE TITLE
Resizing Sample Horizontal Scroll missing when columns are pushed to the right

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular-samples#263]
### Description  
When you resize a column in the resizing column and it pushes the rest of the columns outside of the visible container there is no Horizontal Scrolling available to see the pushed columns.

### Steps to reproduce  

1. Open the Column Resizing Demo
2. Push the fist column almost to the end of the visible screen
3. ...

### Result  
The pushed columns are no longer visible and there is no horizontal scroll available to navigate.

### Expected result  
There should be a horizontal scroll that will allow the user to see the pushed columns

### Attachments  
![resizing](https://user-images.githubusercontent.com/33216749/39125834-0e59d3f8-4709-11e8-8e87-109d6a4d9b12.PNG)

**Comment by skrustev** [comment]
Should be fixed with PR IgniteUI/igniteui-angular#1140.

**Comment by SlavUI** [comment]
This is resolved after the last release

**Comment by PavlovVasil** [comment]
Opening the Resizing sample on https://www.infragistics.com//angularsite/components/grid_column_resizing.html , or on staging, shows that the issue reproduces again.

**Comment by SlavUI** [comment]
Closing as on staging with the latest release it is working correcty
