### ISSUE TITLE
Improve Grid Virtualization and Performance sample

### ISSUE THREAD

**Issue by rkaraivanov** [IgniteUI/igniteui-angular-samples#2635]
### Description  
Improve the sample based on the new features which landed in the grid.

- Use the new currency column type
- Remove the old formatters functions, and use the new pipe arguments input for both the number and currency types.
- Clean up the cell templates.

**Comment by Aleksandyr** [comment]
That issue has been implemented with [this](https://github.com/IgniteUI/igniteui-angular-samples/pull/2497) PR.
