### ISSUE TITLE
Sub-items in Components List are not properly aligned when the width is smaller.

### ISSUE THREAD

**Issue by gedinakova** [IgniteUI/igniteui-angular-samples#266]
### Description  
Data Grid's inner items are not styled properly when the Components list is on top.

### Steps to reproduce  

1. Navigate to 
https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid.html
2. Shrink the browser's width
3. Expand Components List
4. Note Data Grid's sub items

### Result  
Sub items are not properly shown.

### Expected result  
Sub items should still be vertically displayed.

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/16817847/39133132-1f9a508a-471c-11e8-8b28-d5cd5f83d903.png)

**Comment by simeonoff** [comment]
This should be logged under the [docfx](https://github.com/IgniteUI/igniteui-docfx) repository.
