### ISSUE TITLE
Snackbar in TreeGrid Selection samples can't be closed

### ISSUE THREAD

**Issue by igdmdimitrov** [IgniteUI/igniteui-angular-samples#2674]
### Description  
Snackbar in TreeGrid Selection samples can't be closed

### Steps to reproduce  

1. Open [https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/cell-selection](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/cell-selection) or any of the other samples in TreeGrid Selection topics
2. Click on 'Got it, thanks' button in the snackbar of the first sample

### Result  
The snackbar is not closing and error is logged in the console

### Expected result  
The snackbar should be closed with no errors.

**Comment by gedinakova** [comment]
Should be resolved by #2673

**Comment by zdrawku** [comment]
Fixed - https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/cell-selection
