### ISSUE TITLE
Undefined rows appear in the Tree Grid Group By sample with live editing

### ISSUE THREAD

**Issue by DiyanDimitrov** [IgniteUI/igniteui-angular-samples#2709]
### Description  
Undefined rows appear in the Tree Grid Group By sample with live editing.

### Steps to reproduce  

1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/groupby#angular-tree-grid-group-by-example
2. Click LIVE ALL PRICES button.

### Result  
Undefined rows appear.

### Expected result  
No undefined rows should appear.

### Attachments  
![image](https://user-images.githubusercontent.com/43128948/121237419-b6f81900-c89f-11eb-90b7-fa933b418f46.png)

**Comment by gedinakova** [comment]
This issue will be fixed with the changes introduced in [#9625](https://github.com/IgniteUI/igniteui-angular/pull/9625).

**Comment by gedinakova** [comment]
Resolved on staging.
