### ISSUE TITLE
Design for igxAccordion sample(s)

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular-samples#2714]
### Description  

We should determine how many samples are we going to create for the upcoming igxAccordion topic.
Create design for these samples.

[igxAccordion Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Accordion-Specification)

**Comment by StefanIvanov** [comment]
We will be working on the design next sprint but IMO
- We should remove from the Expansion panel topic the section and sample for combining multiple panels and point to the accordion component topic and sample
- We should create one sample with a single expand accordion e.g. FAQ section
- We should create one sample with multiple expand accordion e.g. FAQ section
- We should create one sample to show nested accordions e.g. FAQ section
