### ISSUE TITLE
Design for igxStepper samples

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular-samples#2809]
We should determine how many samples are we going to create for the upcoming igxStepper topic and create design for these samples.

[igStepper Specification](https://github.com/IgniteUI/igniteui-angular/wiki/Stepper-Specification)

**Comment by YoannaIvanova** [comment]
Here is a link to the sample designs in the cloud: https://cloud.indigo.design/share/76temq3fbt7k
