### ISSUE TITLE
Data Grid excel export samples don't load

### ISSUE THREAD

**Issue by zhosti** [IgniteUI/igniteui-angular-samples#2823]
### Description  
The samples for Data Grid excel exporting don't load.

### Steps to reproduce  

Navigate to [Grid Excel Export sample](https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/export-excel#angular-excel-exporter-example)

### Result  
There is no loaded samples.

### Expected result  
Should load excel export samples for Data Grid.

### Attachments  

![Screenshot 2021-10-04 155237](https://user-images.githubusercontent.com/7760119/135854876-d5113d04-9eb5-437c-b459-e791ccf267e2.png)
![Screenshot 2021-10-04 155253](https://user-images.githubusercontent.com/7760119/135854921-0201ad97-ab13-45d4-810e-2ea63932994a.png)

**Comment by gedinakova** [comment]
It turned out to be a staging server issue.
