### ISSUE TITLE
Batch editing samples are not working in Stackblitz/CodeSandbox

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#2847]
Open the Batch editing topic and try to open both topic samples for live-editing.
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/batch-editing

- The first one says that ProductID is not found
- The second one is not opened at all

Same applies to the the editin topic samples:
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing

We might as well need to check all editing samples

**Comment by hanastasov** [comment]
Duplicate of #10240
