### ISSUE TITLE
Grid Editing Style sample - broken styles

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-samples#2885]
### Description  
Describe the issue.

### Steps to reproduce  

1. Go to Grid Editing Style sample
2. Start editing

### Result  
![bug2](https://user-images.githubusercontent.com/14248932/143002384-fd82cf58-590c-4f23-9fea-47dd1b72d7c3.PNG)

### Expected result  
Fix styles to not have this misalignments.

**Comment by desig9stein** [comment]
@hanastasov I am unable to reproduce this behavior on chrome on mac. Which browser are you testing with?

This is how it looks for me in Vnext and Master.
<img width="1296" alt="Screenshot 2022-10-20 at 15 20 46" src="https://user-images.githubusercontent.com/21260963/196947140-077ee957-ddc5-4698-b259-717344ec39f3.png">

**Comment by hanastasov** [comment]
![grid-rediting-styling-issue](https://user-images.githubusercontent.com/14248932/196948876-ed4a90d2-8792-477d-bd91-1dbd0720ac7e.gif)

@desig9stein I am using Chrome Version 106.0.5249.119 (Official Build) (64-bit)
