### ISSUE TITLE
Grid Batch Editing sample - delete button does not work.

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-samples#2886]
Grid Batch Editing sample - delete button does not work.

### Steps to reproduce  

1. Go to Grid Batch Editing sample
2. Click the DELETE button
3. ..

### Result 
Clicking DELETE does not lead to anything:
![bug3](https://user-images.githubusercontent.com/14248932/143002611-568405af-809b-4d19-91fe-10e067e74097.PNG)

### Expected result  
DELETE to actually delete/mar the row as deleted

**Comment by teodosiah** [comment]
@hanastasov looks like everything works as expected now
![delete](https://user-images.githubusercontent.com/52423497/184815809-9f3f3bc6-9b5e-41bc-b7be-fb3f1ca31de8.gif)
