### ISSUE TITLE
grid.component StackBlitz sample does not load in IE11

### ISSUE THREAD

**Issue by mharrington622** [IgniteUI/igniteui-angular-samples#291]
### Description  
Clicking on the StackBlitz button for the [DataGrid](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html) sample while using IE11 does not load correctly.

### Steps to reproduce  

1. Go to [DataGrid Sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html) using IE11.
1. Click on **View on StackBlitz** button.

### Result  
The sample on StackBlitz does not load and IE throws an XSS error.

### Expected result  
No errors should show and the sample should run.

### Notes
I have only noticed this issue with this specific sample, so I'm wondering if the XSS error is due to the randomuser.me dataservice.  It doesn't even look like this service is used in the current sample, so we can try removing it to see if that helps? This is related to IgniteUI/igniteui-docfx#271.

**Comment by tiliev** [comment]
Hello, Mike, thanks for your report. We're working on this. I'll update this issue once we have an update.

**Comment by ig-ealbert** [comment]
https://github.com/stackblitz/core/issues/461

**Comment by apai4** [comment]
stackblitz/core#461 should be resolved, sorry for any issues it may have caused!
