### ISSUE TITLE
Turn off XSS protection

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-angular-samples#292]
Because of this issue https://github.com/IgniteUI/igniteui-docfx/issues/271, please apply "X-XSS-Protection: 0" response to this application, too. It is required since Ignite UI Angular Samples is an endpoint to Ignite UI DocFX and using the live editing files in StackBlitz is prevented by XSS error popping in IE 11.

**Comment by zdrawku** [comment]
Do not close this, we are going to test it on staging and production first.
