### ISSUE TITLE
Add caching to the Remote Virtualization sample

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular-samples#297]
### Description  
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_virtualization.html#grid-remote-virtualization-demo

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_virtualization.html#grid-remote-virtualization-demo
2. Scroll the grid

### Result  
Every scroll generates a remote request

### Expected result  
Add caching so that the requests are less often. For example once on every 5 wheel scrolls

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by sboykova** [comment]
Closed by #353
