### ISSUE TITLE
Error thrown on row edit

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-samples#3004]
1. Go to Grid With Action Strip demo
http://localhost:4200/samples/grid/grid-action-strip
2. Hover a row and click on the Edit button in the Action Strip.

Result: Error in the console:
![image](https://user-images.githubusercontent.com/14248932/169018848-4e2e7ed8-44de-40ae-8dc5-3857c04d797c.png)

**Comment by IvanKitanov17** [comment]
The issue has been fixed with the following PR:

https://github.com/IgniteUI/igniteui-angular-samples/pull/3058
