### ISSUE TITLE
Flickering when entering edit mode in grid

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-samples#3006]
1. Go to Grid Column data types sample
http://localhost:4200/samples/grid/grid-column-data-types

2. Start clicking over cells in the Order Full Date Column

Result: Flickering occurs when entering edit mode:
![editing-flickers](https://user-images.githubusercontent.com/14248932/169022077-7beff4f6-4589-4bc0-b5ae-2d3b2075a8ab.gif)

**Comment by desig9stein** [comment]
@simeonoff @hanastasov The come from a difference in the density of the input group and the grid. In the dev demos the input group in the context of the grid is always in compact density while in the samples browser in SOME samples it uses comfortable and when the grid itself is compact or cosy we see that jump.

**Comment by desig9stein** [comment]
@hanastasov, @simeonoff while a work on input refactoring I noticed that the flickering issue is happening only when the input is wrapped inside the date-picker, for some reason the input-group can't inherit the correct density class.
