### ISSUE TITLE
 TypeError: Cannot read properties of null (reading 'style')

### ISSUE THREAD

**Issue by Volen99** [IgniteUI/igniteui-angular-samples#3015]
### Description  
Drag and dropping a row often throws an error, but the row is successfully dragged 

### Steps to reproduce  

1. Please go to https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/row-drag
2. Open dev tools and drag some rows and observe
3. ![image](https://user-images.githubusercontent.com/41373491/170267172-e0d98b67-0ba3-4c16-9af9-c9702df9df86.png)

**Comment by RivaIvanova** [comment]
This is not a sample-related issue and has been logged in the igniteui-angular repo [here](https://github.com/IgniteUI/igniteui-angular/issues/12004).
