### ISSUE TITLE
Different snippet than the actual code used in the sample

### ISSUE THREAD

**Issue by IvayloG** [IgniteUI/igniteui-angular-samples#3020]
### Description  
Different snippet than the actual code used in the sample.
The toolbar pinning title in the code snippet is
 title="Grid column hiding" BUT in the actual code sample is title="Visible collumns"

### Steps to reproduce  

[Step 1]  [See the snippet](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/toolbar#column-hiding)
[Step 2] [See the sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/toolbar#angular-toolbar-grid-example)

### Result  
Snippet and sample do NOT match.

### Expected result  
Snippet and sample should match, so both are either 
 title="Grid column hiding" **OR** title="Visible collumns"

### Attachments  
![image](https://user-images.githubusercontent.com/4296944/170962516-ded3af77-ee4a-483f-ab4b-0d7193f2022b.png)

**Comment by IvanKitanov17** [comment]
@IvayloG  The samples are using the default behavior, where in the case of the column hiding the default title is "Visible Columns". I believe that in the code snippets is demonstrated that it could be templated, this has been done for the pinning and advanced filtering as well.

**Comment by IvayloG** [comment]
@IvanKitanov17 Oh well, it is acceptable if these go as "showcases" only.
