### ISSUE TITLE
Drag and Drop support for window scroll when dragging element to its edges

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#3037]
### Description  
At the sample for support for window scroll when dragging element to its edges, window scroll is working only when you drag and drop element from bottom to top. When you drag element form the top of the table and drag it to the lower edge, the window is not scrolling. After several attempts, I was not able to drag and drop any elements from the lower part of the table

Browser: chrome 

### Attachments  
![Angular Drag and Drop Sample Bug](https://user-images.githubusercontent.com/52001020/173532108-884eb17e-56ff-43e2-84de-13b87e299668.gif)

**Comment by dkamburov** [comment]
@radomirchev can you please take a look if that's resolved already we can close it
