### ISSUE TITLE
Slider theming sample has a couple of deprecated properties

### ISSUE THREAD

**Issue by 3phase** [IgniteUI/igniteui-angular-samples#3070]
### Description  
The slider theming sample still has some of the properties that were removed in the library.
The samples need to be checked for their existence. 

### Steps to reproduce  

1. Checkout vNext
2. Replace the installed `igniteui-angular` dependency with product of latest master
3. Try to run the samples
4. Observe the errors

### Result  
The following error is arising:
![image](https://user-images.githubusercontent.com/8365193/185108562-59cc2a3d-4485-4495-bc61-073096685c6e.png)

### Expected result  
Samples to run error-free

**Comment by SisIvanova** [comment]
Can't reproduce this issue.
