### ISSUE TITLE
Scrolling issue with the finjs grid

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#3112]
### Description  
When you scroll in the finjs grid with live prices, the scroll is slowly crawling upwards

### Steps to reproduce  

1. Open finjs grid
2. Turn "on" live prices
3. Start scrolling
4. Stop scrolling and observe
![FinTech Grid Dark Scroll Issue](https://user-images.githubusercontent.com/52001020/194502981-8fe46bd3-bf13-44d6-8c63-e272cdfc5019.gif)

**Comment by dkamburov** [comment]
Is it with mouse wheel only?

**Comment by radomirchev** [comment]
> Is it with mouse wheel only?

yes

**Comment by dobromirts** [comment]
The issue can no longer be reproduced.
