### ISSUE TITLE
Not correct description of the Input Group Component

### ISSUE THREAD

**Issue by radomirchev** [IgniteUI/igniteui-angular-samples#3145]
Open: https://www.infragistics.com/products/ignite-ui-angular/angular/components/input-group

The following description is not correct:

The Ignite UI for Angular controls can easily be used in Reactive Forms that provide a model-driven approach for handling form inputs.

**Comment by ChronosSF** [comment]
There is additional feedback on the paragraph:

1. The input group applies prefixes, suffixes and hints, where elements like icons, buttons, custom validation text, etc. can be provided in each
2. The input group can be applied to more than just inputs and selects but also text area so a more complete description would be:
> form input elements, like input, select, textarea, etc.


Please, assign me or Konstantin to review it once you change it and don't make a  PR to master, only vNext
