### ISSUE TITLE
 Summaries are not cleared for column with no data after filtering

### ISSUE THREAD

**Issue by kacheshmarova** [IgniteUI/igniteui-angular-samples#324]
### Description  
Summaries are not cleared for a column that has no records after filtering is applied

### Steps to reproduce  
Open Boston Marathon 2018 sample
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid.html
Filter "Athlete" column so that there are no records left in the grid
Observe 'Top Speed' column summaries

### Result 
There is still summary for this column

### Attachments 
There should be no summary for "Top Speed" column

**Comment by Aleksandyr** [comment]
Duplicated with #325
