### ISSUE TITLE
Staging problems upon testing

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#3320]
Issues with all live-editing samples part of these topics:
- Angular Grid Clipboard Interactions
- Grid column data types
- Grid pinning

Other problems:
Title formatting:
https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/editing

![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/11193764/0395e1f8-024b-497e-a338-7f330ce52832)

**Comment by Svetloslav15** [comment]
Grid Sorting sample in stackblitz: 
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/800539c5-2b1d-410d-bc0b-fe3ac7195221)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/3986d590-a5df-44e8-b064-b1a8a0e4019a)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/26275b21-4980-4928-8b11-8557262c7c9b)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/52b15f63-57e7-4b6e-8e74-7361e754655d)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/82917fc1-a3ef-4476-b86e-216498110c1a)

**Comment by Svetloslav15** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/f38dd5b6-b52a-4602-9290-1c736796a499)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/753829d3-5332-424b-8679-d2f254285938)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/cf363ced-6ee6-4202-b3e0-f41308047c54)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/e5f82616-e2c5-4ed8-b77c-0cac54802d1c)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/57adb23c-0af9-45c1-a6cf-8dfe79dcbf7b)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/0bf8ef37-698f-4337-bee2-4e61824d95d5)

**Comment by Svetloslav15** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/1b854a25-3115-427a-9258-39d024cf83f8)

**Comment by Svetloslav15** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/a2191612-7f16-4625-ac52-c07163af4518)

**Comment by Svetloslav15** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/f2fcaf3f-1125-4f1e-9277-f671780cf965)

**Comment by hanastasov** [comment]
Error: src/app/app.component.html:1:1 - error NG8001: 'app-pivot-grid-state-persistence-sample' is not a known element:
1 <app-pivot-grid-state-persistence-sample></app-pivot-grid-state-persistence-sample>
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


Error: src/app/app.module.ts:13:41 - error TS2307: Cannot find module './pivot-grid/pivot-state-persistence/about.component' or its corresponding type declarations.
13 import { PivotGridAboutComponent } from "./pivot-grid/pivot-state-persistence/about.component";
                                           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: src/app/app.module.ts:28:12 - error NG1010: Value

Error: src/app/pivot-grid/pivot-state-persistence/pivot-grid-state-persistence-sample.component.html:4:13 - error NG8001: 'igx-icon' is not a known element:
4             <igx-icon class="btn-icon">restore</igx-icon>
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: src/app/pivot-grid/pivot-state-persistence/pivot-grid-state-persistence-sample.component.html:11:36 - error NG8002: Can't bind to 'routerLink' since it isn't a known property of 'button'.

11         <button igxButton="raised" [routerLink]="['../pivot-state-about']">



Error: src/app/pivot-grid/pivot-state-persistence/pivot-grid-state-persistence-sample.component.html:37:13 - error NG8001: 'igx-checkbox' is not a known element:

37             <igx-checkbox [checked]="true" (change)="onChange($event, 'toggleAll')">All</igx-checkbox>
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Error: src/app/pivot-grid/pivot-state-persistence/pivot-grid-state-persistence-sample.component.html:37:27 - error NG8002: Can't bind to 'checked' since it isn't a known property of 'igx-checkbox'.
37             <igx-checkbox [checked]="true" (change)="onChange($event, 'toggleAll')">All</igx-checkbox>
                             ~~~~~~~~~~~~~~~~

Error: src/app/pivot-grid/pivot-state-persistence/pivot-grid-state-persistence-sample.component.html:47:1 - error NG8001: 'igx-pivot-grid' is not a known element:



** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/0fcea43f-7fd8-4fa6-beaf-4ee96c8a4ac2)

**Comment by Svetloslav15** [comment]
The sample for tree grid sorting compile successfully but buttons doesn't have styles. https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/sorting
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/f0fe27b9-f952-48df-ac5d-f30d4c40cf3d)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/a5f8d9b4-27c4-4fe7-9c09-6b2e9345cee9)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/4a11f43f-9030-4ddf-b0e5-33bdb0531be2)

**Comment by Svetloslav15** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/e35d9c3e-8679-49ba-b88e-0ce8c8e735e5)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/25d60414-140f-43da-b481-8a3614255e9c)

**Comment by Svetloslav15** [comment]
Tree grid column hiding sample doesn't have the hide button in the stackblitz sample: 
https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/column-hiding
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/9c5cfb99-88b0-426e-956f-ef9e940a71ca)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/c9be80c1-9dde-4a0e-a31c-f936fe9bd67f)

**Comment by Svetloslav15** [comment]
Tree Grid Column Pinning sample compile in stackblitz but don't display anything: 
https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/column-pinning
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/a473cc8c-04dd-494c-9c8e-c415690dade6)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/036d94d6-1bf7-4328-9ddd-73ac14733b91)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/dd4fbb46-1c5e-4d38-a5a4-512ff5a02501)

**Comment by Svetloslav15** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/0f36c033-fa43-4732-b5ce-abc4acfde799)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/436f289a-3b1f-41b3-a537-15d6c6c22797)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/2d7b863c-e303-4186-b8b1-7185dcc624fc)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/702a573b-2585-464f-874c-5b2c833984bc)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/f2b293c0-261f-431b-8317-385da50e8829)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/fb2d77e9-f876-42f5-aacd-01376dac37fc)

**Comment by Svetloslav15** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/ecbbf74d-f77e-44f5-9e70-7bd07d515c54)

**Comment by Svetloslav15** [comment]
Tree Grid Export Visualization sample compile, but one of the buttons doesn't have style: 
https://staging.infragistics.com/products/ignite-ui-angular/angular/components/treegrid/toolbar
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/f215bda7-87bf-45eb-8506-eb38d5e0a63d)

**Comment by katherinedragieva** [comment]
Pagination seems to be missing styling 
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/e93f52c7-0646-4aad-b118-c4f65b847879)

Here looks a bit different
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/fc112075-695d-4710-8be6-e1b5442f4b20)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/e8338f62-62fd-4c23-b1ea-708dde9bff6d)

**Comment by katherinedragieva** [comment]
![Screenshot 2023-05-17 104515](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/627a2707-b5bd-45f5-823d-6fb4841be539)

These buttons should be icons
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/cd14db1d-8bad-44f6-9072-be44729acd63)

**Comment by katherinedragieva** [comment]
Data is not rendered in the appropriate format
![Screenshot 2023-05-17 105356](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/593aaca8-d7bc-4f49-9956-03357aa6d5a0)

![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/2bfd16ce-1154-4fa5-868e-0114418bfa58)

**Comment by katherinedragieva** [comment]
Trying to open Angular Grid Master-Detail Example, but can't load stackblitz sample
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/137c5fe1-afa2-4e1c-81d8-3cf073721939)

![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/82156b8c-ec1d-4ff2-806f-62825781e8d5)

**Comment by katherinedragieva** [comment]
Trying to open Angular Live-data Update Example, but can't load stackblitz sample
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/3152ac0c-0b4f-4ca5-8554-7b2b2a12cd98)

![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/2088474e-ed1b-400a-b61d-0901d634fe92)

**Comment by katherinedragieva** [comment]
Trying to open Live-data feed with Dock Manager and igxGrid Components, but can't load stackblitz sample
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/8c3eea1e-b48c-4d80-8ee2-d7bafad626eb)

![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/686293de-02c8-40fb-bfba-2687076b5871)

**Comment by Svetloslav15** [comment]
Hierarchical Grid State Persistance sample from stackblitz now compile, but buttons doesn't have style: 
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/a2343bc7-c8c1-4668-a5a5-83aba6972f5b)

**Comment by Svetloslav15** [comment]
Button in Grid Export Visualization sample, doen't have style: 
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/54996964-8ffc-49fc-8584-25b9508c1386)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/12e9b394-fd4d-42a7-8533-c87cfb8e7e74)

**Comment by katherinedragieva** [comment]
Doesn't open the calendar pop-up
![Screenshot 2023-05-17 163616](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/c1b5bb7c-3e2a-4535-b815-8f40fab2e016)

**Comment by katherinedragieva** [comment]
The app doesn't look exactly the same as in the site
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/df085611-2ce6-4811-9b4a-139e54cdd7c7)


![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/58e1c509-3f7f-45c5-bb25-ff2118bc0bbc)

**Comment by katherinedragieva** [comment]
Doesn't open the calendar pop-up and missing initial values
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/57befdc3-fa13-491d-8fa5-4df072dfd7fb)

**Comment by Svetloslav15** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/33124382/6a54a123-4f4b-44ab-96b5-b65d54ac4204)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/0fd41803-e51a-4698-9e92-53ec05bb8a4b)

**Comment by katherinedragieva** [comment]
Missing images
![Screenshot 2023-05-18 103411](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/53456031-7b0f-4ae5-a16a-f097fc458d6a)

![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/b495ece0-cd5f-49fa-a144-31b34eca8973)

**Comment by katherinedragieva** [comment]
Missing images
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/125a31b3-3a05-45bc-ba08-b8690c0b0e7b)

![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/2230262c-01aa-4b26-929b-bcab59463b23)

**Comment by katherinedragieva** [comment]
Just a suggestion - can we style the select a bit better, cause right now looks a bit weird
![Screenshot 2023-05-18 112423](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/2eb4967e-befa-4b24-afb4-991aab0f8874)

![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/94e07337-2fbf-400c-8b22-7f2914676c2d)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/3e9be2db-73d7-442e-90de-37079c72c74b)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/490280ed-d559-4f0a-a0f2-48554127e309)

**Comment by katherinedragieva** [comment]
These should be icons 
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/85dd82a9-44db-46a3-8928-bf4b438be7ea)

![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/eff39b35-3911-4f74-9381-13febc57cd57)

**Comment by katherinedragieva** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/14edb9c9-4f26-4a23-84e6-fbf543049637)

**Comment by hanastasov** [comment]
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/14248932/9b1c22be-bb99-4abc-aa55-c13a58148517)

**Comment by katherinedragieva** [comment]
This sample doesn't load at all 
![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/35975071/93ede552-e15d-4226-884e-42446223f17b)

**Comment by zdrawku** [comment]
Everything now fixed
