### ISSUE TITLE
Application samples that should be updated/re-tested with the new product version

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#3433]
Upgrade and re-test the following apps to 17.1.x

- Test CRM and FinJS (live-demo) grids with the new version in the sample browser. **Consider not only an upgrade of the whole samples browser but introducing new functionalities/enhancements based on the new features introduced with the new version.**
- [TaskPlanner](https://github.com/IgniteUI/TaskPlanner) - already upgraded to 17, upgrade to 17.1
- [COVID-19-Dashboard](https://github.com/IgniteUI/COVID-19-Dashboard) 
- [crypto-portfolio-app](https://github.com/IgniteUI/crypto-portfolio-app)  already upgraded to 17,  upgrade to 17.1
- [DockManager-DataAnalysis](https://github.com/IgniteUI/DockManager-DataAnalysis)
- All client app part of the https://github.com/IgniteUI/ASP.NET-Core-Samples/ repository 

Perform Grid performance testing and smoke testing of the following demos:
- [Live-data update](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/live-data#angular-live-data-update-example) grid sample part of the Angular samples
- [Virtualization and performance sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/virtualization)
- [SignalR application](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/how-to/signal-r-service-live-data)
- Server-side rendering testing - [topic](https://www.infragistics.com/products/ignite-ui-angular/angular/components/general/ssr-rendering)

*Ensure there aren't any visual inconsistencies
*No performance hit
*No behavior changes (unless intentional)

**Comment by zdrawku** [comment]
For the DockManager app please pay special attention to why it uses that much GitHub storage:

![image](https://github.com/IgniteUI/igniteui-angular-samples/assets/11193764/f5cfc9ed-3111-4bc5-b62a-7f1c754cfde1)

**Comment by hanastasov** [comment]
Rest of the samples will be handled in task https://github.com/IgniteUI/igniteui-angular-samples/issues/3447
