### ISSUE TITLE
grid-editing sample throws an error.

### ISSUE THREAD

**Issue by MayaKirova** [IgniteUI/igniteui-angular-samples#3511]
### Description  
Sample in docs at : https://staging.infragistics.com/products/ignite-ui-angular/angular/components/grid/cell-editing#angular-grid-cell-editing-and-edit-templates-example
does not load.

When opening the sample itself: https://staging.infragistics.com/angular-demos/grid/grid-editing
It throws an error: 

main.68594ea582fa342f.js:1 ERROR 
TypeError: Cannot read properties of undefined (reading 'open')

**Comment by skrustev** [comment]
Should be fixed by https://github.com/IgniteUI/igniteui-angular/pull/14546

**Comment by dkamburov** [comment]
@tishko0 Please test this and close the bug
