### ISSUE TITLE
Grid landing sample circular progress bar text overlapping the bar

### ISSUE THREAD

**Issue by damyanpetev** [IgniteUI/igniteui-angular-samples#3515]
### Description  
Per the title, could be a component design bit if circular bar font size increased, but assuming that's by design  - then the sample should adjust though proper theme API options, enlarge the row height or change the UI template.

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/grid#angular-data-grid-example
  (FYI jumpy flicker seems to be resolved in latest 18.1.0)
2. Wait for the live data to start hitting 100% Progress
3. Observe the circular progress bars

### Result  
![image](https://github.com/user-attachments/assets/2286f785-ba70-4011-bd0e-ef0434ca6fa3)
Even the double digits barely fit and even if you go with the grid cell default font size of `font-size: .8125rem;` (the bar is set to 1rem) 100% still overlaps a bit.

### Expected result  
The text should comfortably fit in the progress bar or another design should be used for the sample

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by GrblackStar** [comment]
This seems to be fixed as of today?
![image](https://github.com/user-attachments/assets/4a4c7dda-8168-4db5-957d-a78dc15de16f)
