### ISSUE TITLE
Secondary Nav of JP sample leads to English product Page

### ISSUE THREAD

**Issue by DaizenIG** [IgniteUI/igniteui-angular-samples#362]
### Description  
There's a link for Ignite UI for Angular on Secondary Nav on the JP sample page. and it leads to EN product page.

### Steps to reproduce  

1. Go to one of Ignite UI for Angular Page: e.g. https://jp.infragistics.com/products/ignite-ui-angular/angular/components/list.html
2. Click "Ignite UI for Angular" on Secondary Nav 

### Result  
It leads to EN product page - https://infragistics.com/products/ignite-ui-angular/

### Expected result  
It should lead to JP product Page - https://jp.infragistics.com/products/ignite-ui-angular/

### Attachments  
![image](https://user-images.githubusercontent.com/14284406/40523179-6e9cb7c0-600f-11e8-8bd1-9b3de08e2b17.png)

**Comment by yoshimis** [comment]
I was expecting to have it in toc.yml but it is not there. Is it hard-corded? I am assigning to @kdinev. Could you please look into?

**Comment by ig-ealbert** [comment]
https://github.com/IgniteUI/igniteui-docfx-template/blob/master/partials/logo.tmpl.partial

**Comment by tiliev** [comment]
I am currently working on making this hard coded text dynamic. https://github.com/IgniteUI/igniteui-docfx-template/issues/7 is the issue, after we close it I'll set the proper link in the JP version. This will happen in the following 2-3 working days.
