### ISSUE TITLE
[IE] Errors thrown when opening any IgxGrid sample

### ISSUE THREAD

**Issue by rmkrmk** [IgniteUI/igniteui-angular-samples#371]
### Description  
A JS errors are thrown when opening any IgxGrid samples in IE only.
The error is:
ERROR TypeError: Object doesn't support property or method 'forEach'

### Steps to reproduce  

1. Navigate to any IgxGrid sample on the staging, for example:
https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid.html

2. Look at the browser console.

### Result  
JS errors are thrown.

### Expected result  
JS errors should not be thrown.

### Attachments  
![image](https://user-images.githubusercontent.com/11978058/40720852-bb88bd80-6420-11e8-849b-579ae41dd0bb.png)

**Comment by zdrawku** [comment]
IE doesnt support 'forEach':
https://developer.mozilla.org/en-US/docs/Web/API/NodeList/forEach#Browser_Compatibility.

I am going to change this for all samples that are using forEach

**Comment by zdrawku** [comment]
Issue in the Grid, closind this one, opening a [New issue](https://github.com/IgniteUI/igniteui-angular/issues/1436)
