### ISSUE TITLE
Grid Remote Virtualization Demo r

### ISSUE THREAD

**Issue by alexalex972** [IgniteUI/igniteui-angular-samples#372]
### Description  
Describe the issue.

### Steps to reproduce  

1. Step 1
2. Step 2
3. ...

### Result  
What is the actual result after following the steps to reproduce?

### Expected result  
What is the expected result after following the steps to reproduce?

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by zdrawku** [comment]
Duplicate of #374
