### ISSUE TITLE
There is a vertical scrollbar in Paging sample

### ISSUE THREAD

**Issue by mpavlinov** [IgniteUI/igniteui-angular-samples#384]
### Description  
The grid has vertical scrollbar which is unnecessary. 

### Steps to reproduce  

1. Open https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid_paging.html
2. Observe the grid scrollbar

### Result  
There is a vertical scrollbar.

### Expected result  
There should be no vertical scrollbar as the grid demonstrates paging.

**Comment by zdrawku** [comment]
@hanastasov this could be related to the changes we've added to the samples container, last week

**Comment by hanastasov** [comment]
It is not related to that, it is just that the grid height is not enough, will increase it.
