### ISSUE TITLE
Grid GroupBy sample doesn't allow some cells to be selected

### ISSUE THREAD

**Issue by MartinKamenov** [IgniteUI/igniteui-angular-samples#430]
### Description  
Some of the groupBy sample cells are unselectable. The issue is related to this one: https://github.com/IgniteUI/igniteui-angular/issues/1752

### Steps to reproduce  

1. Open groupby sample.
2. Remove the initial group by in the following order:
  - ship city
  - ship country
3. Try to select a cell from the fifth row from the top by clicking on it.

### Result  
The cell on which is clicked isn't selected.

### Expected result  
The cell should be selected after you click on it.

### Attachments  
![one](https://user-images.githubusercontent.com/24592428/42030183-a5a1c8ec-7ada-11e8-8202-69cba8ee13e4.PNG)
![two](https://user-images.githubusercontent.com/24592428/42030198-ad37ab26-7ada-11e8-830b-f32487a0f5be.PNG)
![three](https://user-images.githubusercontent.com/24592428/42030201-aefecd72-7ada-11e8-8bf8-86ab006a6ab3.PNG)

**Comment by mpavlinov** [comment]
@alexalex972 This is fixed in the product. Please verify it after we tag a new beta.
