### ISSUE TITLE
Multi Column Headers samples Sorting is not working

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular-samples#431]
### Description  
Multi Column Headers samples Sorting is not working

### Steps to reproduce  

1. Open the staging 
2. Open Multi column header sample try to sort a couple of columns

### Result  
Multi Column Headers samples Sorting is not working

### Expected result  
Columns should be ableto be sorted

**Comment by zdrawku** [comment]
Issue is fixed in the latest available build (on staging) igniteui "6.1.0-beta.1"
