### ISSUE TITLE
Combo sample's Enable grouping toggle doesn't seem to have any effect

### ISSUE THREAD

**Issue by ChronosSF** [IgniteUI/igniteui-angular-samples#438]
### Steps to reproduce  

1. Open the combo sample on staging
2. Toggle on/off Enable grouping 

### Result  
Neither of the combos have any grouping applied when the toggle is on

### Attachments  
![combo](https://user-images.githubusercontent.com/2188411/42035392-7ab165e6-7aeb-11e8-8af7-3f48c742da69.gif)

**Comment by SlavUI** [comment]
This has been resolved
