### ISSUE TITLE
In Internet Explorer 11 the Editing sample's Date Picker is not visible when adding a new record

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular-samples#447]
### Description  
When you want to add a new record in the Editing sample, the Date Picker is not visible and shows partially if hovered. Only reproducible in Internet Explorer 11

### Steps to reproduce  

1. Open the Grid Editing sample on **staging** 
2. Click the "Add new product" button
3. Click the date so you could pick a date

### Result  
At first it seems nothing happens, but moving the mouse around shows some parts of the Date Picker

### Expected result  
The Date Picker should be fully visible

### Attachments  
![editingcalendar](https://user-images.githubusercontent.com/18643062/42046049-ad5ab0dc-7b05-11e8-93eb-996be37e62e7.gif)

**Comment by simeonoff** [comment]
I am closing this issue as it is resolved in the latest master of igniteui-angular.
