### ISSUE TITLE
In Internet Explorer 11 the elements from the Overlay sample get displaced

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular-samples#448]
### Description  
In Internet Explorer 11 the elements from the Overlay sample get displaced.

### Steps to reproduce  

1. Open the Overlay sample on **staging**

### Result  
The elements get displaced and on top of each other
### Expected result  
The elements should not overlap.

### Attachments  

![overlay](https://user-images.githubusercontent.com/18643062/42046656-05c1c76e-7b07-11e8-9b1d-27b401edba4a.png)

**Comment by ViktorSlavov** [comment]
This has been fixed as the Overlay sample was refactored into separate demos.
