### ISSUE TITLE
navigation page

### ISSUE THREAD

**Issue by jVanZwieten** [IgniteUI/igniteui-angular-samples#46]
### Description  
It would be useful to have a nav bar to navigate through the samples. Currently, you can get to any particular sample by typing its route into the URL, but you have to know its route. Easier/faster to pick from a nav bar.

Would be awesome to have them organized into each control (for controls which have more than 1 sample).

**Comment by kdinev** [comment]
@jVanZwieten The samples are embedded individually in DocFX pages, thus the reason why they are standalone.
