### ISSUE TITLE
igx-linear-bar is not shown in Track Progress column

### ISSUE THREAD

**Issue by sstoyanovIG** [IgniteUI/igniteui-angular-samples#467]
### Description  
igx-linear-bar is not shown in Track Progress column

### Steps to reproduce  

1. Open https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid.html
or 
2. Open https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid_paging.html

### Result  
igx-linear-bar is not shown in Track Progress column

### Expected result  
igx-linear-bar should be visible in Track Progress column

**Comment by hanastasov** [comment]
This is source code style bug - logged https://github.com/IgniteUI/igniteui-angular/issues/1859

**Comment by hanastasov** [comment]
The templated cell need s to be passed width context. Since the template you pass sits inside a parent flex element, it needs to have some width set to it for it to work.
