### ISSUE TITLE
Horizontal scrollbar is not fully visible in Business Propeller sample

### ISSUE THREAD

**Issue by bkulov** [IgniteUI/igniteui-angular-samples#470]
### Description  
The horizontal scrollbar in Business Propeller sample is not fully visible.

### Result  
The horizontal scrollbar in Business Propeller sample is not fully visible.
![small_scrollbar](https://user-images.githubusercontent.com/2705882/42164993-f49903ba-7e0f-11e8-96f8-460975424ca8.png)

### Expected result  
The horizontal scrollbar in Business Propeller sample should be fully visible.

**Comment by mpavlinov** [comment]
@bkulov This is already fixed. You can verify it and close the issue.
