### ISSUE TITLE
mouseWheel on non-scroll grid content causes data lost on Mac

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular-samples#484]
### Description  
When you position the mouse over the grid and start scrolling the page, the result is empty data table container. This is reproducible on **_Mac_**.

### Steps to reproduce  

1. Navigate to Boston Marathon 2018 sample on staging.
2. Position the mouse over the grid
3. Scroll up and down the page

### Result  
Data is lost
### Expected result  
Grid is not affected of page scrolling

**Comment by MayaKirova** [comment]
Reproduces on any environment but only if grid data is changed while scrolling with wheel (live data is enabled).

**Comment by mpavlinov** [comment]
I can replicate it with touch and live data disabled.
