### ISSUE TITLE
Grid Editing sample delete button doesn't work

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular-samples#485]
### Description  
Grid records cannot be deleted in grid Editing sample.
### Steps to reproduce  

1. Navigate to Grid Editing sample on staging
2. Try to delete a record using the trash button

### Result  
The record is not deleted

### Expected result  
The record should be deleted

**Comment by ddincheva** [comment]
This issue is duplicated with #483
