### ISSUE TITLE
Paging bar is cut off on Paging sample

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular-samples#487]
### Description  
Paging bar at the bottom is cut off.

### Steps to reproduce  

1. Navigate to Grid Paging sample on staging.

### Result  
Paging bar height is less than its content (arrows and numbering)

### Expected result  
Paging bar height is enough to fit its content.

### Attachments  
![paging](https://user-images.githubusercontent.com/12935806/42219822-d95ef980-7ed5-11e8-9927-20ee135e1b2d.png)

**Comment by HristoP96** [comment]
Already fixed.
