### ISSUE TITLE
Using delete key on keyboard doesn't ungroup field on Mac when focus is on the chip

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular-samples#491]
### Description  
Delete key doesn't delete the grouped field when the focus is on the chip as per documentation

### Steps to reproduce  

1. Navigate to Grid Group By sample on staging
2. Using the keyboard navigate to the first chip in the grouped area (Ship Country) and make sure it's on focus
3. Press Delete keyboard key 

### Result  
Nothing happens

### Expected result  
The respective chip should be ungrouped

**Comment by mpavlinov** [comment]
This is probably a product bug.

**Comment by tbelcheva** [comment]
Yes, it is. I will move it to the correct repo.
