### ISSUE TITLE
Text is wrapped on multiple lines and crushed when typing in the search input

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular-samples#494]
### Description  
When you start typing in the search box, the date column text is wrapped on multiple lines

### Steps to reproduce  

1. Navigate to grid Searching sample on staging
2. Type in something in the search box

### Result  
Date is wrapped and crushed

### Expected result  
Date is not wrapped

**Comment by gedinakova** [comment]
@tbelcheva I believe this is already resolved. @DDavidkov, please check if this is the case.

**Comment by DDavidkov** [comment]
Yes this is a duplicate issue of [this](https://github.com/IgniteUI/igniteui-angular/issues/1873) one in the main repo. It is already resolved and merged in the 6.1.x branch.
