### ISSUE TITLE
Additional column or some space appears when applying Hiding through Grid Toolbar

### ISSUE THREAD

**Issue by tbelcheva** [IgniteUI/igniteui-angular-samples#495]
### Description  
When you hide several columns using the Grid Toolbar hiding button, there is an empty column at the right end

### Steps to reproduce  
1. Navigate to Grid Toolbar sample on staging
2. Look at the second grid where there are options to hide, pin and export 
3. Hide the first two available columns in the dropdown list

### Result  
An empty column appears on last position

### Expected result  
No additional columns appear

![toolbar](https://user-images.githubusercontent.com/12935806/42268046-3cbe4532-7f83-11e8-99d7-21154a829d6e.png)

**Comment by MayaKirova** [comment]
@mpavlinov IMO this is not a bug. What you see is a white space due to the fact that the sum of the remaining columns is less than the grid width.

**Comment by tbelcheva** [comment]
Ok. I agreed, but it's a little confusing looking like that.
