### ISSUE TITLE
Create Demo for igxToggle

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular-samples#53]

**Comment by sbozalieva** [comment]
![screen shot 2018-02-09 at 11 14 19](https://user-images.githubusercontent.com/23053821/36020167-6d8251ce-0d8a-11e8-9bcb-f7e5515a87ab.png)

**Comment by zdrawku** [comment]
Thank you Tanche, proposed demos looks great, we are going to implement them next sprint
