### ISSUE TITLE
Not enough visible space for the Radio Group Sample

### ISSUE THREAD

**Issue by Aleksandyr** [IgniteUI/igniteui-angular-samples#535]
### Description  
Not enough visible space for the Radio Group Sample

### Steps to reproduce  

1. Open: https://staging.infragistics.local/products/ignite-ui-angular/angular/components/radio_button.html#radio-group-demol

### Attachments  
![capture](https://user-images.githubusercontent.com/7037740/42756278-16750d4a-8904-11e8-9e0d-a42b3962c590.PNG)

**Comment by sboykova** [comment]
Resolved with [#571](https://github.com/IgniteUI/igniteui-docfx/pull/571)
