### ISSUE TITLE
Create some predefined themes

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-samples#595]
### Description  
Please create three or four predefined themes for the samples browser. Those will be changed runtime via certain UI as #131 requires.

**Comment by hanastasov** [comment]
You can use the branch that I pushed [here](https://github.com/IgniteUI/igniteui-angular-samples/pull/598)  to add the themes. There is the docs-layout-component.scss file where I have just put some empty selectors for the predefined themes.

**Comment by StefanIvanov** [comment]
We have created a fluent MS theme with Word and Excel colors, @radomirchev  shall we consider adding another one e.g. iOS inspired or something else? Have there been customer requests related to this?

**Comment by radomirchev** [comment]
@StefanIvanov at the moment there are no customer requests related to new themes, however we will continue to enrich our theme catalog. We could have internal discussion on that.

**Comment by StefanIvanov** [comment]
OK @radomirchev

**Comment by StefanIvanov** [comment]
Issue will be closed once we have PR for [#5990](https://github.com/IgniteUI/igniteui-angular/issues/5990)
