### ISSUE TITLE
Grids with width in % in IE are broken in StackBlitz

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-angular-samples#626]
Open any of the grid samples with width in percent in StackBlitz. It is broken.
More information in this issue - https://github.com/IgniteUI/igniteui-angular/issues/1330.

**Comment by HristoP96** [comment]
Related Issue:
[https://github.com/IgniteUI/igniteui-angular/issues/3095](https://github.com/IgniteUI/igniteui-angular/issues/3095)
