### ISSUE TITLE
Icons are missing 

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#707]
### Description  
Open [cards demo](https://www.infragistics.com/products/ignite-ui-angular/angular/components/card.html) and scroll down

### Result
Icons are missing
![image](https://user-images.githubusercontent.com/11193764/47801834-a79faf00-dd37-11e8-8d09-8e220feeeee3.png)

**Comment by nrobakova** [comment]
The issue is already fixed in the staging
