### ISSUE TITLE
sample for Grid Batch editing cannot be opened in StackBlitz

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular-samples#731]
### Description  
sample for Grid Batch editing cannot be opened in StackBlitz

### Steps to reproduce  

1. Open https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid_batch_editing.html
2. Click on button View On StackBlitz

### Result  
In StackBlitz there is an error:
Error in /turbo_modules/@angular/compiler@6.1.10/bundles/compiler.umd.js (1098:21)
Template parse errors:
'app-grid-with-transactions' is not a known element:
1. If 'app-grid-with-transactions' is an Angular component, then verify that it is part of this module.
2. If 'app-grid-with-transactions' is a Web Component then add 'CUSTOM_ELEMENTS_SCHEMA' to the '@NgModule.schemas' of this component to suppress this message. ("[ERROR ->]<app-grid-with-transactions>
<igx-grid #gridRowEditTransaction [data]="data" [primaryKey]="'Prod"): ng:///AppModule/GridBatchEditingSampleComponent.html@0:0

### Expected result  
Sample should be opened without errors

### Attachments  
Attach a sample if available, and screenshots, if applicable.

**Comment by Lipata** [comment]
https://github.com/IgniteUI/igniteui-angular-samples/pull/717 fixed with this PR
