### ISSUE TITLE
Update the following samples against version 7 update

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#770]
### Description  
Whilte upgrading to angular version 7 and igniteui-angular 7 the following errors and warning appeared. Could you check them:

- [x] **`ElementRef` is missing** 
```
public onInteraction(event) {
	const expandedPanels = this.accordion.filter((panel) => !panel.collapsed);
	expandedPanels.forEach((expandedPanel) => {
		// if (expandedPanel.elementRef !==  event.event.currentTarget) {
		//     expandedPanel.collapse();
		// }
	});
}
```
- [x] **IgxComboComponent, Use of templates warnings on `npm run start`**
```
IgxComboComponent: Setting combo item template with '#emptyTemplate' is depreca         ted.
Use `igxComboEmpty` directive instead.
IgxComboComponent: Setting combo item template with '#headerTemplate' is deprec         ated.
Use `igxComboHeader` directive instead.
IgxComboComponent: Setting combo item template with '#footerTemplate' is deprec         ated.
```

- [x] **Expansion panel**
```
public get getWinningScore(): number {
        // return Math.max(...Object.values(this.currentScore));
    }
```
	
Error: Property values does not exists on type 'ObjectConstructor'

- [x] **Cascading combos:**

```
// @ViewChild("inputCountry") public inputCountry: HTMLInputElement;
// @ViewChild("inputProvince") public inputProvince: HTMLInputElement;
	
```
ReferenceError: HTMLInputElement is not defined
at D:\Dev\igniteui-angular-samples\src\app\combo\cascading-combos\cascading-combos.component.ts:21:53
at Object.<anonymous> (D:\Dev\igniteui-angular-samples\src\app\combo\cascading-combos\cascading-combos.component.ts:17:1)

**Comment by zdrawku** [comment]
[PR](https://github.com/IgniteUI/igniteui-angular-samples/issues/770) with the Update to ng 7, @IvayloG you should wait this PR to be merged and then you can get latest changes and start with this issue

**Comment by ViktorSlavov** [comment]
@zdrawku,
I've addressed points 1,3 and 4 in [this PR](https://github.com/IgniteUI/igniteui-angular-samples/pull/771).
For poitn 2 (deprecation warnings), I think this has been discussed and as far as I understand, they should continue showing up during build, at least for the time being. When you have the time, check out the discussion under [this issues](https://github.com/IgniteUI/igniteui-angular/issues/2915).

**Comment by ViktorSlavov** [comment]
A [rework for the `Deprecate Decorator`](https://github.com/IgniteUI/igniteui-angular/pull/3545) has been merged in the igniteui-angular repo, all of these should not be resolved. Closing this.
