### ISSUE TITLE
Rebuilding with ng 7 throws OutOfMemory exception spontaneously

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#772]
### Description  
[Related PR](https://github.com/IgniteUI/igniteui-angular-samples/pull/780)

`npm run start` throws our of memory exception

Steps to reproduce:

- Get latest master
- Execute npm run start
- Update a sample, do this 2-3 times
-OutOfMemory exception is thrown

**Comment by gmurray81** [comment]
Hmm... I thought @HUSSAR-mtrela already raised the timeout to work around the extended build time.... maybe that was reverted? Still, configured appropriately to work around the source map performance in webpack, it should be building fast enough not to go over the threshold, I would think. Unless the travis VMs are super slow.

**Comment by HUSSAR-mtrela** [comment]
@zdrawku @gmurray81 Yes I did and make sure that the PR that updates to angular 7 did not remove the timeout setting:
https://github.com/IgniteUI/igniteui-angular-samples/blob/master/.travis.yml#L8

**Comment by gmurray81** [comment]
I'd be curious to know why it needs to be raised to that figure given that it builds for you guys much quicker than that locally right? Are the travis VMs just super slow?

**Comment by gmurray81** [comment]
Or is this indicative that there is some difference in the configuration when travis runs the build.

**Comment by igandrews** [comment]
I believe the --prod is slow/long-running locally too and I think it's because it's pulling in all the vendor chunk code.

**Comment by zdrawku** [comment]
> I'd be curious to know why it needs to be raised to that figure given that it builds for you guys much quicker than that locally right? Are the travis VMs just super slow?

Yes @gmurray81, locally the build is passing for less than 4 minutes, and on travis it hangs to more that 30..

**Comment by zdrawku** [comment]
Closing this issue for now, everything went well with the 7.1.1 upgrade. [PR](https://github.com/IgniteUI/igniteui-angular-samples/pull/780)

**Comment by zdrawku** [comment]
Reopening and updating the issue based on latest changes

**Comment by tiliev** [comment]
Currently we fixed this issue by running `gulp generate-live-editing` and `ng serve` commands in a sequential instead of parallel manner. If this issue rises up again, please increase the RAM from 4 GB to 8 GB as mentioned in the previous comment.

**Comment by tiliev** [comment]
This issue seems to persist again. I am going to increase the limit to 8 GB to the remaining commands besides serve and build.
