### ISSUE TITLE
SVG Icon Samples are not loaded in StackBlitz

### ISSUE THREAD

**Issue by npaunov** [IgniteUI/igniteui-angular-samples#781]
### Description  
SVG Icon Samples are not loaded in StackBlitz

### Steps to reproduce  

1. Go to https://www.infragistics.com/products/ignite-ui-angular/angular/components/icon.html
2. Scroll to the bottom of the page where is the SVG Icons samples
3. Click on "View on StackBlitz" button.

### Result  
The icons are not loaded.
There is an error in the console:

"ERROR
Error: Could not fetch SVG from url: https://www.infragistics.com/angular-demos/assets/images/svg/does_not_equal.svg; error: 
Http failure response for (unknown url): 0 Unknown Error"

### Expected result  
The icons are loaded.
No error.

![image](https://user-images.githubusercontent.com/11095014/49365799-59901980-f6f0-11e8-909c-4ebfce47d89c.png)

**Comment by bkulov** [comment]
The actual error in the console is:
Access to fetch at 'https://www.infragistics.com/angular-demos/assets/images/svg/contains.svg' from origin 'https://bxnprdvoadd.angular.stackblitz.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
