### ISSUE TITLE
Grid rendering issue under IE 11

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#793]
### Description  
This issue is related to calculateGridWidth method, responsible to width percentage calculation of columns.

Related issues https://github.com/IgniteUI/igniteui-angular/issues/3317 and https://github.com/IgniteUI/igniteui-angular/issues/3047

For the time being we should add column widths to our grid samples.

https://github.com/IgniteUI/igniteui-angular/issues/3047

**Comment by HristoP96** [comment]
- [ ] Row Editing

- [ ] Grid Paging

- [ ] Grid Filtering

- [ ] Grid Sorting

- [ ] Grid GroupBy (column goes outside the view)

- [ ] Column Resizing

- [ ] Grid Search

- [ ] Grid Toolbar

- [ ] Export to Excel

- [ ] Paste from Excel

- [ ] Multi column headers

- [ ] Conditional Cell Styling

- [ ]
