### ISSUE TITLE
Live Updating Sample Vertical Scroll disappear when you  when it is live

### ISSUE THREAD

**Issue by SlavUI** [IgniteUI/igniteui-angular-samples#805]
### Description  
Live Updating Sample Vertical Scroll disappear when you  when it is live.

### Steps to reproduce  

1. Step 1 open prod or staging
2. Step 2 Go down to the Live Sample and make it Play the data
3. Step 3 Vertical Scroll bar disappears 

### Result  
Vertical Scroll bar disappears 

### Expected result  
Vertical Scroll bar should be visible

### Attachments  

![image](https://user-images.githubusercontent.com/33216749/49745445-a1daa900-fca7-11e8-8a86-32f0fba3c2e4.png)

**Comment by hanastasov** [comment]
Already fixed.
