### ISSUE TITLE
Samples build enhanecements

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#833]
### Description  
Add ` node --max_old_space_size=8192 node_modules/@angular/cli/bin/ng serve --vendor-source-map=false --progress=true --open` to `serve` and `start` in order to skip live-editing generation and increate the old space size parameter.

**Comment by hanastasov** [comment]
Will wait to see if this is necessary to do after introducing lazy loading and bundling in the samples app.

**Comment by zdrawku** [comment]
`max_old_space_size` has been increased already

**Comment by zdrawku** [comment]
I am closing this one, my main intention was to increace the max_old_space_size
