### ISSUE TITLE
Excel Workbooks sample does not work in IE 11

### ISSUE THREAD

**Issue by tiliev** [IgniteUI/igniteui-angular-samples#845]
### Description  
Excel Workbooks sample does not work in IE 11

### Steps to reproduce  

1. Open the docs on staging
2. Go to Frameworks -> Excel library

### Result  
The grid from the first sample is missing

### Expected result  
The grid should be rendered

### Attachments  
![capture](https://user-images.githubusercontent.com/6439482/50344034-f4cb2080-0531-11e9-90f7-acb0c1ad7700.PNG)

**Comment by zdrawku** [comment]
[Fixed](https://www.infragistics.com/products/ignite-ui-angular/angular/components/excel_library.html)
