### ISSUE TITLE
Images doesn't correspond to the samples

### ISSUE THREAD

**Issue by sstoyanovIG** [IgniteUI/igniteui-angular-samples#85]
### Description  
The images in the topic doesn't correspond to the actual samples

### Steps to reproduce  

1. Open https://staging.infragistics.local/products/ignite-ui-angular/angular/components/dialog.html
2. Click "Trigger alert" button

### Result  
The image doesn't correspond to the actual sample

### Expected result  
The image should correspond to the actual sample

**Comment by sbozalieva** [comment]
@sstoyanovIG As discussed I suggest we remove the images from the sample.

**Comment by sstoyanovIG** [comment]
I agree, I will close the issue.
