### ISSUE TITLE
Trying to open the second grid Paging demo in StackBlitz throws an error

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular-samples#850]
### Description  
When trying to open the second grid Paging demo on staging in StackBlitz, an error is thrown and the sample doesn't load.

### Steps to reproduce  

1. Open the samples on staging.
2. Click Data Grid -> Paging
3. Scroll to the bottom and try to open the second demo in StackBlitz

### Result  
There in an error that gets thrown and the demo does not run in StackBlitz - refer to the screenshot below. 

### Expected result  
The demo should load without errors. 

### Attachments  

 
![sketch11](https://user-images.githubusercontent.com/18643062/50347363-fc90c200-053d-11e9-8422-8e29a0d8ca0d.png)

**Comment by HristoP96** [comment]
This issue is already fixed. Open in [staging](https://staging.infragistics.local/products/ignite-ui-angular/angular/components/grid_paging.html#remote-data).
