### ISSUE TITLE
The combo in the Grid Editing sample is only partially visible in MS Edge.

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular-samples#852]
### Description  
When trying to "Add new product" in the Grid Editing sample, the combo in the middle of the dialog is only partially visible in **MS Edge**.

### Steps to reproduce  

1. Open the samples on staging in MS Edge
2. Navigate to Grid Editing sample
3. Click the "Add New Product" button

### Result  
The combo in the middle of the dialog is only partially visible in - refer to the screenshot below.

### Expected result  
The combo input should be fully visible.

### Attachments  

![sketch](https://user-images.githubusercontent.com/18643062/50348441-665e9b00-0541-11e9-99e2-b1e733bcd12e.png)

**Comment by Lipata** [comment]
It seems this is already fixed.
