### ISSUE TITLE
Filtering chips not showing during horizontal scrolling in MS Edge.

### ISSUE THREAD

**Issue by PavlovVasil** [IgniteUI/igniteui-angular-samples#853]
### Description  
When the grid has Filtering enabled and the user scrolls horizontally, the new chips that get into view are not being displayed correctly in **MS Edge**.

### Steps to reproduce  

1. Open the staging samples, or https://www.infragistics.com//angularsite/components/grid_column_hiding.html  in MS Edge
2. Open the Column Hiding sample
3. Scroll slowly to the right

### Result  
The Filtering chips of the last columns are not not shown, or only partially visible - refer to the screenshot below. They get shown correctly only on mouse hover.

### Expected result  
The last chips should be fully visible.

### Attachments  

![sketch4](https://user-images.githubusercontent.com/18643062/50350662-6dd57280-0548-11e9-913c-03c26ba022c7.png)

**Comment by skrustev** [comment]
@simeonoff This seems to be caused by the `filter: opacity(1);` used inside the chip item style. Maybe because the chips that come in view when scrolled are not visible initially and Edge cannot process them?

**Comment by simeonoff** [comment]
The `filter: opacity(1)` prop indicated they are fully opaque at all times. Tbh, this is set as a hack to support the ripple in Safari.

**Comment by skrustev** [comment]
Is there a way for this to be worked around or should we mark this as third party issue and report it to Edge? All other browsers don't have this issue and work correctly in these cases where it is used.

**Comment by simeonoff** [comment]
@skrustev I think I can use another strategy to make the ripple work with oval elements in safari without overflowing.

**Comment by simeonoff** [comment]
This can no longer be reproduced.
