### ISSUE TITLE
Add new demo samples

### ISSUE THREAD

**Issue by hanastasov** [IgniteUI/igniteui-angular-samples#890]
Think of what can be added to existing samples and what new samples to be added to fulfill the below requirements for new samples:

- [x] Grid properties Save / Load. - [Working sample](https://grid-save-state.stackblitz.io/grid-state) - Demonstrate how a developer can save the grid state in terms of column moving, sorting, filt, etc. when user leaves page or close browser, and have the ability to re-load the state when grid reloads.

- [ ] Responsive UI - Demonstrating various RWD examples, like re-template a grid column, hide column, etc, it will alleviate many q’s, benefiting from media queries too.  Similar to https://www.igniteui.com/grid/responsive-web-design-mode

- [x]  [Working sample](https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/paging.html#remote-data) Pager UX - We can modify it further to change button styles, use hyperlinks for page numbers vs. the current UX.  Demonstrating more examples of Pager styling it will help answer q’s. 

- [x] Custom keyboard control - Customizing what happens when Edit Complete (like when Enter key is hit, or Tab key is hit).  For example, going to next cell, cell below, etc.  Demonstrating what API to use to customize key behavior. Done 
https://www.infragistics.com/products/ignite-ui-angular/angular/components/grid/keyboard_navigation.html#custom-keyboard-navigation

Additional samples updated to latest version:
[People app](https://infragistics-indigo-design-sample-people.stackblitz.io/)
[Budget app](https://budget-application.stackblitz.io/)

**Comment by zdrawku** [comment]
@StefanIvanov we've finished with almost all examples, the only one left is Responsive UI. Can you guys help us with it. These samples were mentioned by Jason a while ago, that would be nice to have them on the Angular documentation site.

> Responsive UI - Demonstrating various RWD examples, like re-template a grid column, hide column, etc, it will alleviate many q’s, benefiting from media queries too. Similar to https://www.igniteui.com/grid/responsive-web-design-mode

**Comment by zdrawku** [comment]
We are currently working on other application scenarios, closing this one.
