### ISSUE TITLE
In sample excel_library_working_with_sparklines when export file an error is returned and the exported file is empty

### ISSUE THREAD

**Issue by nrobakova** [IgniteUI/igniteui-angular-samples#909]
### Description  
In sample excel_library_working_with_sparklines when export file an error is returned and the exported file is empty

### Steps to reproduce  

1. Open https://www.infragistics.com//angularsite/components/excel_library_working_with_sparklines.html
2. In the demo click on button "Export to Excel"

### Result  
There is an error in console and the exported file is empty

### Expected result  
File should be exported without errors and should have correct data

### Attachments  
Attach a sample if available, and screenshots, if applicable.  
![image](https://user-images.githubusercontent.com/11463104/51687584-85968f80-1ffb-11e9-9e5d-52f411ec2708.png)

**Comment by HristoP96** [comment]
After a brief investigation for this issue, I saw that the cell chart data is undefined during exporting process: 
![undef](https://user-images.githubusercontent.com/25771040/52349386-225f2100-2a2f-11e9-8245-e61793493667.PNG)

This triggers error on this line:
![er](https://user-images.githubusercontent.com/25771040/52349721-cea10780-2a2f-11e9-88d1-f1083864ac6c.PNG)

**Comment by HUSSAR-mtrela** [comment]
@agoldenbaum can you reproduce this issue and if so did you see implement a fix for it in React samples?

**Comment by nrobakova** [comment]
The issue is not reproducible in the latest samples for 9.1.x
