### ISSUE TITLE
forRoot([]) is not parsed correctly

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#937]
### Description  
Check this [PR](https://github.com/IgniteUI/igniteui-angular-samples/pull), there is a forRoot configuration which is not loaded correctly in stackblitz.

Actual result in StackBlitz:
`ngImports: [RouterModule.forRoot(), IgxGridModule.forRoot(), HttpClientModule],`

Expected result:
`ngImports: [RouterModule.forRoot([]), IgxGridModule.forRoot(), HttpClientModule],`

**Comment by tiliev** [comment]
We are not able to extract such information from the type. Please use the type, enclosed in quotation marks, as a string, if you need to provide an empty array as an argument:
```
"RouterModule.forRoot([])"
```
