### ISSUE TITLE
Update 'npm start' command

### ISSUE THREAD

**Issue by zdrawku** [IgniteUI/igniteui-angular-samples#977]
### Description  
Update the current “npm start” definition. Run live-editing would be removed and the build will behave as ng serve. A new command should be introduces to be used by all developers.

- Update the TFS builds if needed
- Add the new command that will be used for live-editing generation

**Comment by tiliev** [comment]
After discussion with @zdrawku, it's been decided the new command will be `npm run start:live-editing`.
